{
  "hash": "3ce111af3303a0791bcb00253cc83ef4",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"In-class Exercise 6: Emerging Hot Spot Analysis\"\nauthor: \"Ji Guofang\"\ndate: \"October 3, 2026\"\ndate-modified: \"last-modified\"\nformat:\n  html:\n    toc: true\n    toc-depth: 4\n    toc-expand: true\nexecute:\n  echo: true\n  eval: true\n  warning: false\n  freeze: auto\neditor: visual\n---\n\n## Overview\n\n[Hands-on Exercise 5a](../../hand-on-ex/hand-on-ex5/hand-on-ex5a.qmd) and [5b](../../hand-on-ex/hand-on-ex5/hand-on-ex5b.qmd) worked through the measures of spatial association on one year of Hunan data: global Moran's I and Geary's C, their permutation tests, local Moran's I, the LISA cluster map, and hot and cold spot analysis with Getis-Ord Gi\\*. All of that is assumed here and none of it is repeated.\n\nWhat those exercises could not answer is whether a hot spot is *new*. Gi\\* computed on GDPPC in 2012 says that the north-east of the province was a significant concentration of wealth that year. It says nothing about whether the concentration had been there since 2005, had been building steadily, or had just appeared. A planner deciding where to intervene needs that distinction, because a long-standing hot spot and an emerging one call for different responses.\n\nEmerging Hot Spot Analysis supplies it by running the Gi\\* machinery over a panel instead of a cross-section, and then testing each location's Gi\\* *time series* for trend. The method has four steps:\n\n- build a space-time cube, which is the panel with its geometry attached,\n- compute Gi\\* for every location in every time period,\n- test each location's sequence of Gi\\* values for monotonic trend with the Mann-Kendall test, and\n- classify each location by combining the trend result with the pattern of significant bins over time.\n\nThis exercise follows all four on seventeen years of Hunan GDPPC, first by hand so that the pieces are visible, and then through `emerging_hotspot_analysis()` of **sfdep**, which does the whole thing in one call. The two routes turn out not to agree, and the last section is about why.\n\n## Getting Started\n\nSix packages are used:\n\n| Package | Role |\n|----|----|\n| **sf** | Importing and reprojecting the boundary layer |\n| **sfdep** | The space-time cube, the Gi\\* statistic and the one-call EHSA |\n| **tmap** | Mapping the classification |\n| **plotly** | Making the single-county trend plot readable by hover |\n| **tidyverse** | Data import and wrangling |\n| **Kendall** | The Mann-Kendall trend test |\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(sf, sfdep, tmap,\n               plotly, tidyverse,\n               Kendall)\n```\n:::\n\n\n**spdep** does not appear, for the same reason as in [Exercise 5b](../../hand-on-ex/hand-on-ex5/hand-on-ex5b.qmd): **sfdep** wraps it and returns results as list columns in a data frame, which is what makes a per-year `group_by()` possible below. **Kendall** is the one genuinely new dependency, and it supplies a single function.\n\n## The Data\n\n| Dataset | Description |\n|----|----|\n| `Hunan` | County boundary layer of Hunan province, China, in ESRI shapefile format |\n| `Hunan_GDPPC.csv` | GDP per capita by county and year, 2005 to 2021 |\n\nThe boundary layer is the one carried through Exercises 4 and 5. The attribute table is new, and the difference is the whole point: `Hunan_2012.csv` held one value per county, while this file holds seventeen.\n\n### Importing geospatial data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhunan <- st_read(dsn = \"data/geospatial\",\n                 layer = \"Hunan\") %>%\n  st_transform(crs = 32650)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `Hunan' from data source \n  `C:\\Users\\Imgigi\\Desktop\\629\\in-class-ex\\in-class-ex6\\data\\geospatial' \n  using driver `ESRI Shapefile'\nSimple feature collection with 88 features and 7 fields\nGeometry type: POLYGON\nDimension:     XY\nBounding box:  xmin: 108.7831 ymin: 24.6342 xmax: 114.2544 ymax: 30.12812\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n:::\n\n\n88 counties, reprojected to EPSG 32650, WGS 84 / UTM zone 50N. [Exercise 5a](../../hand-on-ex/hand-on-ex5/hand-on-ex5a.qmd) deliberately left the layer in geographic coordinates because contiguity does not depend on the coordinate system. Here it must be projected, because the weights built below are inverse *distance* weights and a distance computed from degrees of latitude and longitude is not a distance.\n\n### Importing attribute table\n\n\n::: {.cell}\n\n```{.r .cell-code}\nGDPPC <- read_csv(\"data/aspatial/Hunan_GDPPC.csv\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(GDPPC)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 1,496\nColumns: 3\n$ Year   <dbl> 2005, 2005, 2005, 2005, 2005, 2005, 2005, 2005, 2005, 2005, 200…\n$ County <chr> \"Longshan\", \"Changsha\", \"Wangcheng\", \"Ningxiang\", \"Liuyang\", \"Z…\n$ GDPPC  <dbl> 3469, 24612, 14659, 11687, 13406, 8546, 10944, 8040, 7383, 1168…\n```\n\n\n:::\n:::\n\n\nThree columns and 1,496 rows: 88 counties by 17 years, with no gaps. The panel is balanced, which the next step requires.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(GDPPC$GDPPC)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n   3315   11895   20941   26705   34163  155564 \n```\n\n\n:::\n:::\n\n\nGDPPC runs from 3,315 to 155,564 yuan across the whole panel. The provincial median rose from 7,308 in 2005 to 43,227 in 2021, a factor of 5.9, and Changsha is the richest county in both years at 24,612 and 144,309. That province-wide growth is exactly why the analysis runs on Gi\\* rather than on GDPPC itself. Every county's GDPPC trends upward, so a trend test on the raw values would find a significant increase almost everywhere and say nothing. Gi\\* is a *relative* measure, standardised against the whole study area in each year, so a rising Gi\\* means a county is pulling ahead of the province rather than merely growing.\n\n## Creating a Time Series Cube\n\n`spacetime()` of **sfdep** binds the attribute panel to the geometry, keeping them as two linked contexts rather than joining them into one wide table:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nGDPPC_st <- spacetime(GDPPC, hunan,\n                      .loc_col = \"County\",\n                      .time_col = \"Year\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nis_spacetime_cube(GDPPC_st)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n:::\n\n\n`TRUE` confirms the object is a true cube. The check is not a formality: a cube requires every location to appear in every time period, so one county missing one year would make the object fail here. The practical reason it matters is that Gi\\* is computed within each year against all the other counties in that year, and a missing county would silently change the comparison set for that year only.\n\nThe object has two contexts, `\"data\"` and `\"geometry\"`, and `activate()` chooses which one a verb applies to. The geometry context holds 88 rows, one per county, while the data context holds all 1,496.\n\n## Computing Gi\\*\n\n### Deriving the spatial weights\n\nThe neighbours and weights are built once, on the geometry context, and then apply to every year:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nGDPPC_nb <- GDPPC_st %>%\n  activate(\"geometry\") %>%\n  mutate(nb = include_self(\n    st_contiguity(geometry)),\n    wt = st_inverse_distance(nb,\n                             geometry,\n                             scale = 1,\n                             alpha = 1),\n    .before = 1) %>%\n  set_nbs(\"nb\") %>%\n  set_wts(\"wt\")\n```\n:::\n\n\nTwo details carry real weight. `include_self()` is what makes the statistic Gi\\* rather than Gi: Gi measures the concentration in a county's *neighbourhood excluding itself*, while Gi\\* includes the county, which is what is wanted when asking whether a place and its surroundings together form a hot spot. Adding self raises the average neighbourhood from 5.09 counties to 6.09, ranging from 2 to 12.\n\n`st_inverse_distance()` then replaces the binary contiguity with weights that decay as 1/d, so an adjacent county whose centroid is close counts for more than one that is adjacent but distant. This differs from [Exercise 5b](../../hand-on-ex/hand-on-ex5/hand-on-ex5b.qmd), where the Gi\\* used a fixed distance band with equal weights inside it.\n\n`set_nbs()` and `set_wts()` register the two columns with the cube so that the data context can see them. A plain `mutate()` would attach them to the geometry context only, and the grouped computation below would not find them.\n\n### Computing Gi\\* for every county and year\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\ngi_stars <- GDPPC_nb %>%\n  group_by(Year) %>%\n  mutate(gi_star = local_gstar_perm(\n    GDPPC, nb, wt)) %>%\n  tidyr::unnest(gi_star)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwrite_rds(gi_stars, \"data/rds/gi_stars.rds\")\ngi_stars <- read_rds(\"data/rds/gi_stars.rds\")\n```\n:::\n\n\n`group_by(Year)` is doing the work. Without it, `local_gstar_perm()` would treat all 1,496 rows as one spatial dataset and standardise a county's 2005 value against every other county in every other year, which would turn the whole exercise into a measure of how early the observation was taken. With it, each year is standardised against itself, and the result is 1,496 Gi\\* values that are comparable across years by construction.\n\nThe seed is set because `local_gstar_perm()` draws permutations. Only the simulated p-values depend on it, since the Gi\\* values themselves are deterministic, but a seeded document is a reproducible one.\n\nGi\\* over the whole panel runs from -2.888 to 6.579.\n\n## Mann-Kendall Test\n\nThe Mann-Kendall test asks whether a series is monotonically increasing or decreasing. It compares every pair of observations and counts how many pairs rise with time against how many fall, so it is a rank test: it cares about direction, not magnitude, and it assumes nothing about the distribution of the values. That suits a Gi\\* series, which is not normal and has no reason to be linear.\n\n### One county first\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncbg <- gi_stars %>%\n  ungroup() %>%\n  filter(County == \"Changsha\") |>\n  select(County, Year, gi_star)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = cbg,\n       aes(x = Year,\n           y = gi_star)) +\n  geom_line() +\n  theme_light()\n```\n\n::: {.cell-output-display}\n![](in-class-ex6_files/figure-html/unnamed-chunk-12-1.png){width=768}\n:::\n:::\n\n\nChangsha's Gi\\* starts at 5.03 in 2005 and ends at 5.75 in 2021, peaking at 6.58 in 2019. It is a strong hot spot throughout, which is no surprise for the provincial capital, and the question the test answers is whether it is getting *more* so.\n\nAn interactive version makes the individual years readable, which a static line at this scale does not:\n\n\n::: {.cell}\n\n```{.r .cell-code}\np <- ggplot(data = cbg,\n       aes(x = Year,\n           y = gi_star)) +\n  geom_line() +\n  theme_light()\n\nggplotly(p)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"plotly html-widget html-fill-item\" id=\"htmlwidget-94a1e27ac577598af369\" style=\"width:100%;height:406px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-94a1e27ac577598af369\">{\"x\":{\"data\":[{\"x\":[2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021],\"y\":[5.0282995066289047,5.1692011079782345,5.2958892892912894,5.6039537096873993,6.2788862246004742,5.9357455762937326,5.7508709054298892,5.6942475830114576,5.7085054237054784,5.7608121561733521,6.097127241257188,6.0036547779673146,6.2028053540357906,6.0371816202738318,6.579432171885526,5.7669155664195504,5.7486534794156494],\"text\":[\"Year: 2005<br />gi_star: 5.028300\",\"Year: 2006<br />gi_star: 5.169201\",\"Year: 2007<br />gi_star: 5.295889\",\"Year: 2008<br />gi_star: 5.603954\",\"Year: 2009<br />gi_star: 6.278886\",\"Year: 2010<br />gi_star: 5.935746\",\"Year: 2011<br />gi_star: 5.750871\",\"Year: 2012<br />gi_star: 5.694248\",\"Year: 2013<br />gi_star: 5.708505\",\"Year: 2014<br />gi_star: 5.760812\",\"Year: 2015<br />gi_star: 6.097127\",\"Year: 2016<br />gi_star: 6.003655\",\"Year: 2017<br />gi_star: 6.202805\",\"Year: 2018<br />gi_star: 6.037182\",\"Year: 2019<br />gi_star: 6.579432\",\"Year: 2020<br />gi_star: 5.766916\",\"Year: 2021<br />gi_star: 5.748653\"],\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(0,0,0,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"showlegend\":false,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null}],\"layout\":{\"margin\":{\"t\":23.305936073059364,\"r\":7.3059360730593621,\"b\":37.260273972602747,\"l\":43.105022831050242},\"plot_bgcolor\":\"rgba(255,255,255,1)\",\"paper_bgcolor\":\"rgba(255,255,255,1)\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724},\"xaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[2004.2,2021.8],\"tickmode\":\"array\",\"ticktext\":[\"2005\",\"2010\",\"2015\",\"2020\"],\"tickvals\":[2005,2010,2015,2020],\"categoryorder\":\"array\",\"categoryarray\":[\"2005\",\"2010\",\"2015\",\"2020\"],\"nticks\":null,\"ticks\":\"outside\",\"tickcolor\":\"rgba(179,179,179,1)\",\"ticklen\":3.6529680365296811,\"tickwidth\":0.33208800332088001,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":11.68949771689498},\"tickangle\":-0,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"gridcolor\":\"rgba(222,222,222,1)\",\"gridwidth\":0.33208800332088001,\"zeroline\":false,\"anchor\":\"y\",\"title\":{\"text\":\"Year\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724}},\"hoverformat\":\".2f\"},\"yaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[4.9507428733660737,6.656988805148357],\"tickmode\":\"array\",\"ticktext\":[\"5.0\",\"5.5\",\"6.0\",\"6.5\"],\"tickvals\":[5,5.5,6,6.5],\"categoryorder\":\"array\",\"categoryarray\":[\"5.0\",\"5.5\",\"6.0\",\"6.5\"],\"nticks\":null,\"ticks\":\"outside\",\"tickcolor\":\"rgba(179,179,179,1)\",\"ticklen\":3.6529680365296811,\"tickwidth\":0.33208800332088001,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":11.689497716894984},\"tickangle\":-0,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"gridcolor\":\"rgba(222,222,222,1)\",\"gridwidth\":0.33208800332088001,\"zeroline\":false,\"anchor\":\"x\",\"title\":{\"text\":\"gi_star\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724}},\"hoverformat\":\".2f\"},\"shapes\":[{\"type\":\"rect\",\"fillcolor\":\"rgba(255,255,255,1)\",\"line\":{\"color\":\"rgba(179,179,179,1)\",\"width\":0.66417600664176002,\"linetype\":\"solid\"},\"yref\":\"paper\",\"xref\":\"paper\",\"layer\":\"below\",\"x0\":0,\"x1\":1,\"y0\":0,\"y1\":1}],\"showlegend\":false,\"legend\":{\"bgcolor\":\"rgba(255,255,255,1)\",\"bordercolor\":\"transparent\",\"borderwidth\":1.8897637795275593,\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":11.68949771689498}},\"hovermode\":\"closest\",\"barmode\":\"relative\"},\"config\":{\"doubleClick\":\"reset\",\"modeBarButtonsToAdd\":[\"hoverclosest\",\"hovercompare\"],\"showSendToCloud\":false},\"source\":\"A\",\"attrs\":{\"7f0860b22030\":{\"x\":{},\"y\":{},\"type\":\"scatter\"}},\"cur_data\":\"7f0860b22030\",\"visdat\":{\"7f0860b22030\":[\"function (y) \",\"x\"]},\"highlight\":{\"on\":\"plotly_click\",\"persistent\":false,\"dynamic\":false,\"selectize\":false,\"opacityDim\":0.20000000000000001,\"selected\":{\"opacity\":1},\"debounce\":0},\"shinyEvents\":[\"plotly_hover\",\"plotly_click\",\"plotly_selected\",\"plotly_relayout\",\"plotly_brushed\",\"plotly_brushing\",\"plotly_clickannotation\",\"plotly_doubleclick\",\"plotly_deselect\",\"plotly_afterplot\",\"plotly_sunburstclick\"],\"base_url\":\"https://plot.ly\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncbg %>%\n  summarise(mk = list(\n    unclass(\n      Kendall::MannKendall(gi_star)))) %>%\n  tidyr::unnest_wider(mk)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 5\n    tau      sl     S     D  varS\n  <dbl>   <dbl> <dbl> <dbl> <dbl>\n1 0.485 0.00742    66  136.  589.\n```\n\n\n:::\n:::\n\n\nKendall's tau is 0.485 with a p-value of 0.0074, so the upward trend is significant at the 0.05 level. The other three columns are the internals: `S` is 66, the excess of rising pairs over falling ones, out of `D` = 136 comparable pairs, and `varS` is the variance of `S` under the null of no trend. A tau of 0.485 means roughly three quarters of the year pairs rise.\n\nThe substantive reading is that Changsha was already the strongest hot spot in the province in 2005 and became stronger still. Provincial growth has not been evenly shared.\n\n### Every county at once\n\nThe same summary, grouped:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nehsa_mk <- gi_stars %>%\n  group_by(County) %>%\n  summarise(mk = list(\n    unclass(\n      Kendall::MannKendall(gi_star)))) %>%\n  tidyr::unnest_wider(mk)\nhead(ehsa_mk)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 6\n  County        tau        sl     S     D  varS\n  <chr>       <dbl>     <dbl> <dbl> <dbl> <dbl>\n1 Anhua      0.191  0.303        26  136.  589.\n2 Anren     -0.294  0.108       -40  136.  589.\n3 Anxiang    0      1             0  136.  589.\n4 Baojing   -0.691  0.000128    -94  136.  589.\n5 Chaling   -0.0882 0.650       -12  136.  589.\n6 Changning -0.750  0.0000318  -102  136.  589.\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nehsa_mk %>%\n  summarise(n = n(),\n            significant = sum(sl < 0.05),\n            rising = sum(sl < 0.05 & tau > 0),\n            falling = sum(sl < 0.05 & tau < 0))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 4\n      n significant rising falling\n  <int>       <int>  <int>   <int>\n1    88          42     20      22\n```\n\n\n:::\n:::\n\n\n42 of the 88 counties show a significant trend in their Gi\\*, 20 upward and 22 downward. The near balance is what a relative measure forces: Gi\\* is standardised within each year, so a county can only gain relative standing if others lose it. The province is polarising rather than converging, and the test locates both ends of that movement.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nemerging <- ehsa_mk %>%\n  arrange(sl, abs(tau)) %>%\n  slice(1:10)\nemerging\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 6\n   County        tau         sl     S     D  varS\n   <chr>       <dbl>      <dbl> <dbl> <dbl> <dbl>\n 1 Shuangfeng  0.868 0.00000143   118  136.  589.\n 2 Xiangtan    0.868 0.00000143   118  136.  589.\n 3 Xiangxiang  0.868 0.00000143   118  136.  589.\n 4 Chengbu    -0.824 0.00000482  -112  136.  589.\n 5 Dongan     -0.824 0.00000482  -112  136.  589.\n 6 Wugang     -0.809 0.00000712  -110  136.  589.\n 7 Huayuan    -0.794 0.0000105   -108  136.  589.\n 8 Shaoshan    0.794 0.0000105    108  136.  589.\n 9 Liuyang     0.779 0.0000153    106  136.  589.\n10 Zhuzhou     0.765 0.0000221    104  136.  589.\n```\n\n\n:::\n:::\n\n\n::: callout-note\n## This slice is not a list of emerging hot spots\n\nThe object is conventionally named `emerging`, and the sort does not produce what the name suggests. `arrange(sl, abs(tau))` orders by p-value ascending, so it returns the ten *strongest* trends, and strength here is signed in both directions. Six of these ten are rising, Shuangfeng, Xiangtan, Xiangxiang, Shaoshan, Liuyang and Zhuzhou, and four are falling, Chengbu, Dongan, Wugang and Huayuan. Reading the table as a shortlist of emerging hot spots would put four counties with sharply *declining* relative standing at the top of it.\n\nA second point applies to the 42 counties above as well. Eighty-eight Mann-Kendall tests are run and none of the p-values is adjusted, so at a 0.05 threshold roughly four significant results are expected by chance alone. The classification produced by `emerging_hotspot_analysis()` below does apply a correction internally, which is one of several reasons the two sets of results do not line up.\n:::\n\n## Performing Emerging Hotspot Analysis\n\nEverything above is packaged into one function:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\nehsa <- emerging_hotspot_analysis(\n  x = GDPPC_st,\n  .var = \"GDPPC\",\n  k = 1,\n  nsim = 99\n)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwrite_rds(ehsa, \"data/rds/ehsa.rds\")\nehsa <- read_rds(\"data/rds/ehsa.rds\")\n```\n:::\n\n\n`k = 1` is the number of time lags included in each bin's neighbourhood, so with `k = 1` a county's 2012 neighbourhood contains its neighbours in 2012 *and* in 2011. `nsim = 99` sets the permutations behind the p-value. The seed is set for the same reason as before.\n\n### Visualising the distribution of EHSA classes\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = ehsa,\n       aes(y = fct_rev(fct_infreq(classification)))) +\n  geom_bar() +\n  labs(x = \"Counties\", y = NULL) +\n  theme_light()\n```\n\n::: {.cell-output-display}\n![](in-class-ex6_files/figure-html/unnamed-chunk-20-1.png){width=768}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nehsa %>%\n  count(classification, sort = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 2\n  classification          n\n  <chr>               <int>\n1 sporadic coldspot      47\n2 sporadic hotspot       24\n3 oscilating hotspot     11\n4 oscilating coldspot     4\n5 consecutive hotspot     1\n6 no pattern detected     1\n```\n\n\n:::\n:::\n\n\nSix classes appear. `sporadic coldspot` takes 47 of the 88 counties and `sporadic hotspot` 24, so 71 counties are classified as on-again, off-again. Only one county, Suining, is a `consecutive hotspot`, and 15 are oscillating, meaning they have been significant in both directions at different times. The class names are spelled `oscilating` in the output, with one l, and that is **sfdep**'s spelling rather than a transcription slip.\n\nThe dominance of the sporadic classes is informative rather than disappointing. Seventeen years is long enough for a county's relative position to drift in and out of significance, and a class that requires an unbroken run is correspondingly hard to earn.\n\n### Visualising EHSA\n\nThe classification is joined back to the geometry, and only the significant counties are coloured:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhunan_ehsa <- hunan %>%\n  left_join(ehsa,\n            by = join_by(County == location))\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nehsa_sig <- hunan_ehsa %>%\n  filter(p_value < 0.05)\n\ntm_shape(hunan_ehsa) +\n  tm_polygons(fill = \"grey95\") +\n  tm_borders(fill_alpha = 0.5) +\ntm_shape(ehsa_sig) +\n  tm_polygons(fill = \"classification\",\n              fill.scale = tm_scale_categorical(\n                values = \"brewer.set2\"),\n              fill.legend = tm_legend(\n                title = \"EHSA class\",\n                position = tm_pos_in(\"left\", \"bottom\"))) +\n  tm_borders(fill_alpha = 0.4) +\n  tm_title(\"Emerging hot spot classes, significant at 0.05\")\n```\n\n::: {.cell-output-display}\n![](in-class-ex6_files/figure-html/unnamed-chunk-23-1.png){width=864}\n:::\n:::\n\n\nTwo `tm_shape()` calls are stacked deliberately. The first draws all 88 counties in pale grey so the province keeps its shape, and the second overpaints only the 44 counties whose trend is significant. Filtering before mapping rather than mapping all 88 and relying on transparency is what keeps the insignificant counties from reading as a class of their own.\n\n44 of the 88 counties are significant: 19 sporadic cold spots, 15 sporadic hot spots, 6 oscillating hot spots, 2 oscillating cold spots, the single consecutive hot spot, and one county classed `no pattern detected` whose trend is nonetheless significant.\n\n### Interpretation of the classes\n\nThe classes answer a different question from the trend test, and the difference is worth stating plainly:\n\n| Class | Meaning |\n|----|----|\n| `consecutive hotspot` | An unbroken run of significant hot spot periods at the end of the series, never a significant cold spot |\n| `sporadic hotspot` | On-again, off-again hot spot, never a significant cold spot |\n| `oscilating hotspot` | A recent hot spot that was a significant cold spot at some earlier point |\n| `sporadic coldspot` | On-again, off-again cold spot, never a significant hot spot |\n| `oscilating coldspot` | A recent cold spot that was a significant hot spot earlier |\n| `no pattern detected` | The trend test does not place the location in any of the above |\n\nA class describes the *history* of significance, and tau describes the *direction* of movement. The two can disagree without either being wrong. Hengshan is a `sporadic coldspot` with tau of +0.53: it has spent the period as an intermittently significant cold spot while steadily closing the gap. That combination, a poor neighbourhood catching up, is invisible to the single-year Gi\\* map of [Exercise 5b](../../hand-on-ex/hand-on-ex5/hand-on-ex5b.qmd) and is arguably the most useful thing the method produces.\n\n## The two routes do not give the same answer\n\nThe exercise computed Mann-Kendall by hand and then called a function that computes Mann-Kendall, and the natural assumption is that the second confirms the first. It does not.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncomparison <- ehsa %>%\n  as_tibble() %>%\n  select(location, classification, ehsa_tau = tau, p_value) %>%\n  left_join(ehsa_mk %>% select(location = County, manual_tau = tau),\n            by = \"location\")\n\ncomparison %>%\n  summarise(n = n(),\n            correlation = round(cor(ehsa_tau, manual_tau), 3),\n            same_sign = round(mean(sign(ehsa_tau) == sign(manual_tau)), 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n      n correlation same_sign\n  <int>       <dbl>     <dbl>\n1    88      -0.056     0.455\n```\n\n\n:::\n:::\n\n\nThe two tau columns are uncorrelated, and they agree on the direction of the trend for fewer than half the counties. Individual cases are stark:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncomparison %>%\n  filter(location %in% c(\"Changsha\", \"Shuangfeng\", \"Nan\", \"Li\")) %>%\n  select(location, manual_tau, ehsa_tau, classification)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 4\n  location   manual_tau ehsa_tau classification    \n  <chr>           <dbl>    <dbl> <chr>             \n1 Li             0.0294   -0.824 sporadic coldspot \n2 Shuangfeng     0.868    -0.471 sporadic hotspot  \n3 Nan           -0.0147    0.912 sporadic hotspot  \n4 Changsha       0.485     0.779 oscilating hotspot\n```\n\n\n:::\n:::\n\n\nShuangfeng has the joint strongest rising trend in the manual table at +0.87 and the function reports -0.47 for it. Nan is flat by hand at -0.01 and +0.91 by the function.\n\n::: callout-warning\n## It is a different statistic, not a bookkeeping error\n\nThe obvious suspicion is that the rows have been lined up wrongly, because `ehsa` is ordered as the boundary layer is while `ehsa_mk` is alphabetical. That was checked and ruled out. The join above is by county name, not by position, and the two sets of tau values are not even the same numbers in a different order: sorting both vectors and comparing them gives no match, and re-ordering the manual table into the order the source CSV uses agrees with the function on 2 counties out of 88.\n\nWhat the comparison does show is that the function's tau moves with `k`, the time-lag parameter, which the manual computation has no equivalent of:\n\n| | k = 1 | k = 2 | k = 3 | k = 4 |\n|----|----|----|----|----|\n| correlation with the `k = 1` result | 1.000 | 0.973 | 0.946 | 0.920 |\n| correlation with the manual tau | -0.056 | -0.060 | -0.039 | -0.028 |\n| counties significant at 0.05 | 44 | 34 | 31 | 33 |\n\nThe function's tau is highly stable against a change in `k` and completely unrelated to the hand computation at every value of it. That is the signature of a statistic computed on a different series: `emerging_hotspot_analysis()` builds each bin's neighbourhood in space *and* time, pooling the current period with the previous `k`, so the Gi\\* series it tests is not the per-year Gi\\* series built above. Changing `k` also moves 19 of the 88 classifications between `k = 1` and `k = 2`.\n\nThe practical conclusion is that the manual walkthrough explains the *idea* of EHSA and does not reproduce the *output* of the function. The step-by-step version is worth doing because it makes the space-time cube, the per-year Gi\\*, and the trend test concrete, but the numbers it yields should not be reported alongside the classification as though they were two views of one result. If the classification is what is being used, `k` is a modelling choice that has to be stated, and the default of 1 is a choice like any other.\n:::\n\n## Reference\n\n- Kam, T. S. *R for Geospatial Data Science and Analytics*, [Chapter 11: Emerging Hot Spot Analysis](https://r4gdsa.netlify.app/chap11).\n- [Understanding Emerging Hotspots](https://sfdep.josiahparry.com/articles/understanding-emerging-hotspots), the **sfdep** article that defines the classification used above.\n- [`emerging_hotspot_analysis`](https://sfdep.josiahparry.com/reference/emerging_hotspot_analysis.html) and [`spacetime`](https://sfdep.josiahparry.com/reference/spacetime.html) in the **sfdep** reference.\n- Mann, H. B. (1945) \"Nonparametric Tests Against Trend\", *Econometrica*, 13(3): 245-259.\n- Kendall, M. G. (1975) *Rank Correlation Methods*, 4th edition, Charles Griffin, London.\n- Getis, A. and Ord, J. K. (1992) [\"The Analysis of Spatial Association by Use of Distance Statistics\"](https://onlinelibrary.wiley.com/doi/10.1111/j.1538-4632.1992.tb00261.x), *Geographical Analysis*, Vol. 24, No. 3, pp. 189-206.\n",
    "supporting": [
      "in-class-ex6_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/htmltools-fill-0.5.9/fill.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/htmlwidgets-1.6.4/htmlwidgets.js\"></script>\n<script src=\"../../site_libs/plotly-binding-4.12.0/plotly.js\"></script>\n<script src=\"../../site_libs/typedarray-0.1/typedarray.min.js\"></script>\n<script src=\"../../site_libs/jquery-3.5.1/jquery.min.js\"></script>\n<link href=\"../../site_libs/crosstalk-1.2.2/css/crosstalk.min.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/crosstalk-1.2.2/js/crosstalk.min.js\"></script>\n<link href=\"../../site_libs/plotly-htmlwidgets-css-2.25.2/plotly-htmlwidgets.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/plotly-main-2.25.2/plotly-latest.min.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}