<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.26">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Ji Guofang">
<meta name="dcterms.date" content="2026-09-19">

<title>Hands-on Exercise 3: Spatio-Temporal Point Patterns Analysis – ISSS626-GAA</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-b63d4034c3481c87820d918ed17e6fb1.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<!-- Set the language attribute BEFORE the body paints, so a reader who chose
     中文 does not see a flash of English first. The button and its handler
     live in _include/lang-toggle.html, which is injected after the body. -->
<script>
(function () {
  var l = "en";
  try { l = localStorage.getItem("isss626-th1-lang") || "en"; } catch (e) {}
  if (l !== "en" && l !== "zh") l = "en";
  document.documentElement.setAttribute("data-lang", l);
})();
</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">ISSS626-GAA</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-hands-on-exercise" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Hands-on Exercise</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-hands-on-exercise">    
        <li>
    <a class="dropdown-item" href="../../hand-on-ex/hand-on-ex1/hand-on-ex1.html">
 <span class="dropdown-text">Exercise 1a · Geospatial Data Science with R</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../hand-on-ex/hand-on-ex1/hand-on-ex1b.html">
 <span class="dropdown-text">Exercise 1b · Thematic Mapping and GeoVisualisation</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li>
    <a class="dropdown-item" href="../../hand-on-ex/hand-on-ex2/hand-on-ex2a.html">
 <span class="dropdown-text">Exercise 2a · 1st Order Spatial Point Patterns Analysis</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../hand-on-ex/hand-on-ex2/hand-on-ex2b.html">
 <span class="dropdown-text">Exercise 2b · 2nd Order Spatial Point Patterns Analysis</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li>
    <a class="dropdown-item" href="../../hand-on-ex/hand-on-ex3/hand-on-ex3.html">
 <span class="dropdown-text">Exercise 3 · Spatio-Temporal Point Patterns Analysis</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li>
    <a class="dropdown-item" href="../../hand-on-ex/hand-on-ex4/hand-on-ex4.html">
 <span class="dropdown-text">Exercise 4 · Spatial Weights and Applications</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li>
    <a class="dropdown-item" href="../../hand-on-ex/hand-on-ex5/hand-on-ex5a.html">
 <span class="dropdown-text">Exercise 5a · Global Measures of Spatial Autocorrelation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../hand-on-ex/hand-on-ex5/hand-on-ex5b.html">
 <span class="dropdown-text">Exercise 5b · Local Measures of Spatial Autocorrelation</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-in-class-exercise" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">In-class Exercise</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-in-class-exercise">    
        <li>
    <a class="dropdown-item" href="../../in-class-ex/in-class-ex1/in-class-ex1.html">
 <span class="dropdown-text">Exercise 1 · Analytical Maps and the Raster Data Model</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li>
    <a class="dropdown-item" href="../../in-class-ex/in-class-ex4/in-class-ex4.html">
 <span class="dropdown-text">Exercise 4 · Geographically Weighted Summary Statistics</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-take-home-exercise" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Take-home Exercise</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-take-home-exercise">    
        <li>
    <a class="dropdown-item" href="../../take-home-ex/take-home-ex1/take-home-ex1.html">
 <span class="dropdown-text">Exercise 1 · Technical Report</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../take-home-ex/take-home-ex1/take-home-ex1-slides.html">
 <span class="dropdown-text">Exercise 1 · Executive Summary</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active" data-toc-expanded="99">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#overview" id="toc-overview" class="nav-link active" data-scroll-target="#overview">Overview</a></li>
  <li><a href="#learning-outcome" id="toc-learning-outcome" class="nav-link" data-scroll-target="#learning-outcome">Learning Outcome</a>
  <ul>
  <li><a href="#the-research-questions" id="toc-the-research-questions" class="nav-link" data-scroll-target="#the-research-questions">The research questions</a></li>
  </ul></li>
  <li><a href="#the-data" id="toc-the-data" class="nav-link" data-scroll-target="#the-data">The Data</a></li>
  <li><a href="#installing-and-loading-the-r-packages" id="toc-installing-and-loading-the-r-packages" class="nav-link" data-scroll-target="#installing-and-loading-the-r-packages">Installing and Loading the R Packages</a></li>
  <li><a href="#importing-and-preparing-study-area" id="toc-importing-and-preparing-study-area" class="nav-link" data-scroll-target="#importing-and-preparing-study-area">Importing and Preparing Study Area</a>
  <ul>
  <li><a href="#importing-study-area" id="toc-importing-study-area" class="nav-link" data-scroll-target="#importing-study-area">Importing study area</a></li>
  <li><a href="#converting-to-owin" id="toc-converting-to-owin" class="nav-link" data-scroll-target="#converting-to-owin">Converting to owin</a></li>
  </ul></li>
  <li><a href="#importing-and-preparing-forest-fire-data" id="toc-importing-and-preparing-forest-fire-data" class="nav-link" data-scroll-target="#importing-and-preparing-forest-fire-data">Importing and Preparing Forest Fire Data</a></li>
  <li><a href="#visualising-the-fire-points" id="toc-visualising-the-fire-points" class="nav-link" data-scroll-target="#visualising-the-fire-points">Visualising the Fire Points</a>
  <ul>
  <li><a href="#overall-plot" id="toc-overall-plot" class="nav-link" data-scroll-target="#overall-plot">Overall plot</a></li>
  <li><a href="#visualising-geographic-distribution-of-forest-fires-by-month" id="toc-visualising-geographic-distribution-of-forest-fires-by-month" class="nav-link" data-scroll-target="#visualising-geographic-distribution-of-forest-fires-by-month">Visualising geographic distribution of forest fires by month</a></li>
  </ul></li>
  <li><a href="#computing-stkde-by-month" id="toc-computing-stkde-by-month" class="nav-link" data-scroll-target="#computing-stkde-by-month">Computing STKDE by Month</a>
  <ul>
  <li><a href="#extracting-forest-fires-by-month" id="toc-extracting-forest-fires-by-month" class="nav-link" data-scroll-target="#extracting-forest-fires-by-month">Extracting forest fires by month</a></li>
  <li><a href="#creating-ppp" id="toc-creating-ppp" class="nav-link" data-scroll-target="#creating-ppp">Creating ppp</a></li>
  <li><a href="#including-owin-object" id="toc-including-owin-object" class="nav-link" data-scroll-target="#including-owin-object">Including owin object</a></li>
  <li><a href="#computing-spatio-temporal-kde" id="toc-computing-spatio-temporal-kde" class="nav-link" data-scroll-target="#computing-spatio-temporal-kde">Computing spatio-temporal KDE</a></li>
  <li><a href="#plotting-the-spatio-temporal-kde-object" id="toc-plotting-the-spatio-temporal-kde-object" class="nav-link" data-scroll-target="#plotting-the-spatio-temporal-kde-object">Plotting the spatio-temporal KDE object</a></li>
  </ul></li>
  <li><a href="#computing-stkde-by-day-of-year" id="toc-computing-stkde-by-day-of-year" class="nav-link" data-scroll-target="#computing-stkde-by-day-of-year">Computing STKDE by Day of Year</a>
  <ul>
  <li><a href="#creating-ppp-object" id="toc-creating-ppp-object" class="nav-link" data-scroll-target="#creating-ppp-object">Creating ppp object</a></li>
  <li><a href="#including-owin-object-1" id="toc-including-owin-object-1" class="nav-link" data-scroll-target="#including-owin-object-1">Including owin object</a></li>
  <li><a href="#computing-the-stkde" id="toc-computing-the-stkde" class="nav-link" data-scroll-target="#computing-the-stkde">Computing the STKDE</a></li>
  </ul></li>
  <li><a href="#computing-stkde-by-day-of-year-improved-method" id="toc-computing-stkde-by-day-of-year-improved-method" class="nav-link" data-scroll-target="#computing-stkde-by-day-of-year-improved-method">Computing STKDE by Day of Year: Improved Method</a>
  <ul>
  <li><a href="#computing-spatio-temporal-kde-1" id="toc-computing-spatio-temporal-kde-1" class="nav-link" data-scroll-target="#computing-spatio-temporal-kde-1">Computing spatio-temporal KDE</a></li>
  <li><a href="#plotting-the-output-spatio-temporal-kde" id="toc-plotting-the-output-spatio-temporal-kde" class="nav-link" data-scroll-target="#plotting-the-output-spatio-temporal-kde">Plotting the output spatio-temporal KDE</a></li>
  </ul></li>
  <li><a href="#spatio-temporal-point-patterns-analysis-stpp-methods" id="toc-spatio-temporal-point-patterns-analysis-stpp-methods" class="nav-link" data-scroll-target="#spatio-temporal-point-patterns-analysis-stpp-methods">Spatio-temporal Point Patterns Analysis: stpp Methods</a>
  <ul>
  <li><a href="#preparing-spatio-temporal-point-process-object-of-stpp" id="toc-preparing-spatio-temporal-point-process-object-of-stpp" class="nav-link" data-scroll-target="#preparing-spatio-temporal-point-process-object-of-stpp">Preparing spatio-temporal point process object of stpp</a></li>
  <li><a href="#computing-spatio-temporal-k-function" id="toc-computing-spatio-temporal-k-function" class="nav-link" data-scroll-target="#computing-spatio-temporal-k-function">Computing spatio-temporal K-function</a></li>
  <li><a href="#guide-to-interpret-the-plot" id="toc-guide-to-interpret-the-plot" class="nav-link" data-scroll-target="#guide-to-interpret-the-plot">Guide to interpret the plot</a></li>
  </ul></li>
  <li><a href="#reference" id="toc-reference" class="nav-link" data-scroll-target="#reference">Reference</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content column-page-left" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Hands-on Exercise 3: Spatio-Temporal Point Patterns Analysis</h1>
</div>



<div class="quarto-title-meta column-page-left">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Ji Guofang </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 19, 2026</p>
    </div>
  </div>
  
    <div>
    <div class="quarto-title-meta-heading">Modified</div>
    <div class="quarto-title-meta-contents">
      <p class="date-modified">September 19, 2026</p>
    </div>
  </div>
    
  </div>
  


</header>


<section id="overview" class="level2">
<h2 class="anchored" data-anchor-id="overview">Overview</h2>
<p>A spatio-temporal point process, also called a space-time or spatial-temporal point process, is a random collection of points where each point represents the <strong>time and location</strong> of an event. Examples include the incidence of disease, sightings or births of a species, and the occurrence of fires, earthquakes, lightning strikes, tsunamis or volcanic eruptions.</p>
<p>The analysis of spatio-temporal point patterns is becoming increasingly necessary given the rapid emergence of geographically and temporally indexed data. This exercise combines several R packages to run a set of spatio-temporal point pattern analyses, using real-world forest fire events in Kepulauan Bangka Belitung, Indonesia from 1 January 2023 to 31 December 2023.</p>
</section>
<section id="learning-outcome" class="level2">
<h2 class="anchored" data-anchor-id="learning-outcome">Learning Outcome</h2>
<section id="the-research-questions" class="level3">
<h3 class="anchored" data-anchor-id="the-research-questions">The research questions</h3>
<p>The specific questions to be answered are:</p>
<ul>
<li>Are the locations of forest fire in Kepulauan Bangka Belitung spatially and spatio-temporally independent?</li>
<li>If the answer is NO, where and when do the observed forest fire locations tend to cluster?</li>
</ul>
</section>
</section>
<section id="the-data" class="level2">
<h2 class="anchored" data-anchor-id="the-data">The Data</h2>
<p>Two data sets are used:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Dataset</th>
<th>Description</th>
<th>Source</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>forestfires.csv</code></td>
<td>Locations of forest fires detected by the Moderate Resolution Imaging Spectroradiometer (MODIS) sensor. Only fires within Kepulauan Bangka Belitung are used.</td>
<td><a href="https://firms.modaps.eosdis.nasa.gov/">FIRMS</a></td>
</tr>
<tr class="even">
<td><code>Kepulauan_Bangka_Belitung</code></td>
<td>ESRI shapefile of the sub-district (kelurahan) boundaries of Kepulauan Bangka Belitung</td>
<td>Indonesia Geospatial portal</td>
</tr>
</tbody>
</table>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>How this copy of the data differs from the textbook’s
</div>
</div>
<div class="callout-body-container callout-body">
<p>The textbook’s files come from the Indonesia Geospatial portal and FIRMS’ authenticated archive. Neither is scriptable without an account, so the same two layers were rebuilt from open sources: the boundaries from <strong>GADM 4.1</strong> at level 4, which is the kelurahan/desa level, and the fires from the <strong>FIRMS country archive</strong> for Indonesia 2023, clipped to the province.</p>
<p>The result is close but not identical, and the difference is worth stating:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th>This exercise</th>
<th>Textbook</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Boundary polygons</td>
<td>362</td>
<td>297</td>
</tr>
<tr class="even">
<td>Fire detections</td>
<td>898</td>
<td>741</td>
</tr>
<tr class="odd">
<td>Eastern extent</td>
<td>108.85 E</td>
<td>106.85 E</td>
</tr>
</tbody>
</table>
<p>The extent is the substantive difference. Belitung island lies between 107.5 E and 108.3 E, so the textbook’s boundary, despite the name Kepulauan Bangka Belitung, stops short of it and covers Bangka alone. Clipping to Bangka only gives 766 fires, which is much nearer the textbook’s 741; the remaining 132 fires are on Belitung.</p>
<p>The whole province is used here, since that is what the dataset is called and what the research question asks about. Every figure below therefore differs from the textbook’s, and the selected bandwidths differ with them.</p>
</div>
</div>
</section>
<section id="installing-and-loading-the-r-packages" class="level2">
<h2 class="anchored" data-anchor-id="installing-and-loading-the-r-packages">Installing and Loading the R Packages</h2>
<p>Six packages are used:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Package</th>
<th>Role</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>sf</strong></td>
<td>Importing, processing and wrangling geospatial data</td>
</tr>
<tr class="even">
<td><strong>raster</strong></td>
<td>Handling raster data in R</td>
</tr>
<tr class="odd">
<td><strong>spatstat</strong></td>
<td>Spatial point patterns analysis</td>
</tr>
<tr class="even">
<td><strong>sparr</strong></td>
<td>Fixed and adaptive kernel-smoothed spatial relative risk surfaces, and fixed-bandwidth spatio-temporal density estimation</td>
</tr>
<tr class="odd">
<td><strong>tmap</strong></td>
<td>Cartographic quality thematic maps</td>
</tr>
<tr class="even">
<td><strong>tidyverse</strong></td>
<td>Data import, transformation, wrangling and visualisation</td>
</tr>
</tbody>
</table>
<p><strong>stpp</strong> is added to the list for the space-time K-function in the final section.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(sf, raster, spatstat, sparr, stpp, tmap, tidyverse)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>raster</strong> appears in the textbook’s package list but no raster object is created anywhere in this chapter, since the density surfaces stay as <code>sparr</code> objects and are drawn with base <code>plot()</code>. It is loaded here for consistency with the textbook, not because it is needed.</p>
</div>
</div>
</section>
<section id="importing-and-preparing-study-area" class="level2">
<h2 class="anchored" data-anchor-id="importing-and-preparing-study-area">Importing and Preparing Study Area</h2>
<section id="importing-study-area" class="level3">
<h3 class="anchored" data-anchor-id="importing-study-area">Importing study area</h3>
<p>The shapefile is imported, dissolved into a single outline with <code>st_union()</code>, stripped of its Z dimension, and reprojected to <strong>WGS 84 / UTM zone 48S</strong> (EPSG: 32748), the projected system appropriate for this part of Indonesia:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>kbb_sf <span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="at">dsn =</span> <span class="st">"data/rawdata"</span>,</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>                  <span class="at">layer =</span> <span class="st">"Kepulauan_Bangka_Belitung"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_union</span>() <span class="sc">%&gt;%</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_zm</span>(<span class="at">drop =</span> <span class="cn">TRUE</span>, <span class="at">what =</span> <span class="st">"ZM"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_transform</span>(<span class="at">crs =</span> <span class="dv">32748</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Reading layer `Kepulauan_Bangka_Belitung' from data source 
  `C:\Users\Imgigi\Desktop\629\hand-on-ex\hand-on-ex3\data\rawdata' 
  using driver `ESRI Shapefile'
Simple feature collection with 362 features and 7 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 105.108 ymin: -3.416535 xmax: 108.848 ymax: -1.501757
Geodetic CRS:  WGS 84</code></pre>
</div>
</div>
<p><code>st_union()</code> matters here. The observation window for a point pattern must be a single region, not a collection of several hundred sub-district polygons, so the boundaries are dissolved before conversion.</p>
</section>
<section id="converting-to-owin" class="level3">
<h3 class="anchored" data-anchor-id="converting-to-owin">Converting to owin</h3>
<p><code>as.owin()</code> converts <code>kbb_sf</code> into an <code>owin</code> object:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>kbb_owin <span class="ot">&lt;-</span> <span class="fu">as.owin</span>(kbb_sf)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>kbb_owin</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>window: polygonal boundary
enclosing rectangle: [512010.4, 928107.4] x [9621858, 9833989] units</code></pre>
</div>
</div>
<p><code>class()</code> confirms the output is indeed an <code>owin</code> object:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(kbb_owin)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "owin"</code></pre>
</div>
</div>
</section>
</section>
<section id="importing-and-preparing-forest-fire-data" class="level2">
<h2 class="anchored" data-anchor-id="importing-and-preparing-forest-fire-data">Importing and Preparing Forest Fire Data</h2>
<p>The CSV carries longitude and latitude as ordinary columns, so <code>st_as_sf()</code> is used to build the geometry, declaring the coordinates as wgs84 before reprojecting to match the study area:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>fire_sf <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/rawdata/forestfires.csv"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_as_sf</span>(<span class="at">coords =</span> <span class="fu">c</span>(<span class="st">"longitude"</span>, <span class="st">"latitude"</span>),</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">crs =</span> <span class="dv">4326</span>) <span class="sc">%&gt;%</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_transform</span>(<span class="at">crs =</span> <span class="dv">32748</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>A <code>ppp</code> object accepts only numeric or character values as marks, so the acquisition date is converted into three separate numeric and factor fields:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>fire_sf <span class="ot">&lt;-</span> fire_sf <span class="sc">%&gt;%</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">DayofYear =</span> <span class="fu">yday</span>(acq_date)) <span class="sc">%&gt;%</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Month_num =</span> <span class="fu">month</span>(acq_date)) <span class="sc">%&gt;%</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Month_fac =</span> <span class="fu">month</span>(acq_date,</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>                           <span class="at">label =</span> <span class="cn">TRUE</span>,</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>                           <span class="at">abbr =</span> <span class="cn">FALSE</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="visualising-the-fire-points" class="level2">
<h2 class="anchored" data-anchor-id="visualising-the-fire-points">Visualising the Fire Points</h2>
<section id="overall-plot" class="level3">
<h3 class="anchored" data-anchor-id="overall-plot">Overall plot</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(kbb_sf) <span class="sc">+</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_polygons</span>(<span class="at">fill =</span> <span class="st">"grey95"</span>, <span class="at">col =</span> <span class="st">"grey60"</span>, <span class="at">lwd =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_shape</span>(fire_sf) <span class="sc">+</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_dots</span>(<span class="at">size =</span> <span class="fl">0.15</span>, <span class="at">fill =</span> <span class="st">"firebrick"</span>, <span class="at">fill_alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_title</span>(<span class="st">"Forest fire detections, Kepulauan Bangka Belitung, 2023"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="hand-on-ex3_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="864"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="visualising-geographic-distribution-of-forest-fires-by-month" class="level3">
<h3 class="anchored" data-anchor-id="visualising-geographic-distribution-of-forest-fires-by-month">Visualising geographic distribution of forest fires by month</h3>
<p><code>tm_facets()</code> splits the same map by the month factor, so the seasonal movement of the fires becomes visible:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(kbb_sf) <span class="sc">+</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_polygons</span>(<span class="at">fill =</span> <span class="st">"grey95"</span>, <span class="at">col =</span> <span class="st">"grey70"</span>, <span class="at">lwd =</span> <span class="fl">0.4</span>) <span class="sc">+</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_shape</span>(fire_sf) <span class="sc">+</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_dots</span>(<span class="at">size =</span> <span class="fl">0.1</span>, <span class="at">fill =</span> <span class="st">"firebrick"</span>, <span class="at">fill_alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_facets_wrap</span>(<span class="at">by =</span> <span class="st">"Month_fac"</span>,</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>                 <span class="at">ncol =</span> <span class="dv">4</span>,</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>                 <span class="at">free.coords =</span> <span class="cn">FALSE</span>,</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>                 <span class="at">drop.units =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="hand-on-ex3_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="1056"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="computing-stkde-by-month" class="level2">
<h2 class="anchored" data-anchor-id="computing-stkde-by-month">Computing STKDE by Month</h2>
<p>This section computes the spatio-temporal KDE using <code>spattemp.density()</code> of the <strong>sparr</strong> package.</p>
<section id="extracting-forest-fires-by-month" class="level3">
<h3 class="anchored" data-anchor-id="extracting-forest-fires-by-month">Extracting forest fires by month</h3>
<p><code>as.ppp()</code> needs only the mark field and the geometry field, so the unwanted columns are dropped first:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>fire_month <span class="ot">&lt;-</span> fire_sf <span class="sc">%&gt;%</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Month_num)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="creating-ppp" class="level3">
<h3 class="anchored" data-anchor-id="creating-ppp">Creating ppp</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>fire_month_ppp <span class="ot">&lt;-</span> <span class="fu">as.ppp</span>(fire_month)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>fire_month_ppp</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Marked planar point pattern: 898 points
marks are numeric, of storage type  'double'
window: rectangle = [521564.1, 862416.4] x [9642001, 9828767] units</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fire_month_ppp)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Marked planar point pattern:  898 points
Average intensity 1.410627e-08 points per square unit

Coordinates are given to 10 decimal places

marks are numeric, of type 'double'
Summary:
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  1.000   8.000   9.000   8.643  10.000  12.000 

Window: rectangle = [521564.1, 862416.4] x [9642001, 9828767] units
                    (340900 x 186800 units)
Window area = 63659700000 square units</code></pre>
</div>
</div>
<p>Checking for duplicated point events:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">any</span>(<span class="fu">duplicated</span>(fire_month_ppp))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] FALSE</code></pre>
</div>
</div>
</section>
<section id="including-owin-object" class="level3">
<h3 class="anchored" data-anchor-id="including-owin-object">Including owin object</h3>
<p>Combining the point events with the study area window:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>fire_month_owin <span class="ot">&lt;-</span> fire_month_ppp[kbb_owin]</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fire_month_owin)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Marked planar point pattern:  898 points
Average intensity 5.357491e-08 points per square unit

Coordinates are given to 10 decimal places

marks are numeric, of type 'double'
Summary:
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  1.000   8.000   9.000   8.643  10.000  12.000 

Window: polygonal boundary
270 separate polygons (no holes)
             vertices        area relative.area
polygon 1        8736 1.15970e+10      6.92e-01
polygon 2           6 5.15790e+04      3.08e-06
polygon 3           7 9.35325e+04      5.58e-06
polygon 4          20 1.26679e+04      7.56e-07
polygon 5          23 9.26107e+04      5.53e-06
polygon 6          18 4.98850e+05      2.98e-05
polygon 7          30 3.37290e+04      2.01e-06
polygon 8          54 3.25363e+05      1.94e-05
polygon 9          33 1.30250e+06      7.77e-05
polygon 10        132 1.16490e+06      6.95e-05
polygon 11         69 1.91355e+05      1.14e-05
polygon 12        117 1.51905e+05      9.06e-06
polygon 13         95 1.14409e+05      6.83e-06
polygon 14         22 4.54503e+03      2.71e-07
polygon 15         25 1.18153e+04      7.05e-07
polygon 16        131 1.52345e+05      9.09e-06
polygon 17         39 1.07779e+04      6.43e-07
polygon 18         54 3.46837e+05      2.07e-05
polygon 19         72 2.15853e+05      1.29e-05
polygon 20         16 1.85061e+03      1.10e-07
polygon 21         79 1.05702e+05      6.31e-06
polygon 22         20 4.26450e+03      2.54e-07
polygon 23        119 1.64729e+05      9.83e-06
polygon 24         40 1.16146e+04      6.93e-07
polygon 25         16 3.52284e+03      2.10e-07
polygon 26        328 3.08592e+06      1.84e-04
polygon 27        191 2.36937e+06      1.41e-04
polygon 28         77 8.82506e+04      5.27e-06
polygon 29         49 6.13179e+04      3.66e-06
polygon 30        121 7.64910e+04      4.56e-06
polygon 31          5 1.73815e+04      1.04e-06
polygon 32       5944 4.61753e+09      2.75e-01
polygon 33          4 6.39020e+03      3.81e-07
polygon 34         16 1.18396e+05      7.06e-06
polygon 35          5 2.11407e+04      1.26e-06
polygon 36         11 3.52360e+04      2.10e-06
polygon 37         13 6.20570e+04      3.70e-06
polygon 38          8 1.23128e+04      7.35e-07
polygon 39          5 9.16907e+03      5.47e-07
polygon 40         31 1.54528e+06      9.22e-05
polygon 41         13 6.02786e+04      3.60e-06
polygon 42         19 8.71573e+04      5.20e-06
polygon 43         15 6.16242e+04      3.68e-06
polygon 44          8 1.56726e+04      9.35e-07
polygon 45          6 1.35363e+04      8.08e-07
polygon 46          4 4.29360e+03      2.56e-07
polygon 47         23 1.77052e+05      1.06e-05
polygon 48         45 4.35839e+04      2.60e-06
polygon 49          5 6.83224e+03      4.08e-07
polygon 50          5 6.68328e+03      3.99e-07
polygon 51          5 2.25570e+03      1.35e-07
polygon 52          7 2.61716e+04      1.56e-06
polygon 53          9 1.20125e+04      7.17e-07
polygon 54          8 2.24884e+04      1.34e-06
polygon 55          6 1.21058e+04      7.22e-07
polygon 56          5 8.79539e+03      5.25e-07
polygon 57          9 2.28045e+04      1.36e-06
polygon 58          6 9.20554e+03      5.49e-07
polygon 59         49 1.00131e+05      5.97e-06
polygon 60          5 4.47493e+03      2.67e-07
polygon 61          4 2.88084e+03      1.72e-07
polygon 62          4 3.66452e+03      2.19e-07
polygon 63         69 9.92186e+04      5.92e-06
polygon 64          5 3.03623e+03      1.81e-07
polygon 65          6 1.05413e+04      6.29e-07
polygon 66          8 9.42911e+03      5.63e-07
polygon 67         13 6.94883e+04      4.15e-06
polygon 68         34 2.01331e+05      1.20e-05
polygon 69        227 1.23408e+06      7.36e-05
polygon 70          4 2.59824e+03      1.55e-07
polygon 71          7 8.47540e+03      5.06e-07
polygon 72          5 8.12486e+03      4.85e-07
polygon 73         95 2.08341e+05      1.24e-05
polygon 74         18 7.79145e+04      4.65e-06
polygon 75         24 1.59007e+04      9.49e-07
polygon 76          4 8.81028e+02      5.26e-08
polygon 77         43 4.25653e+04      2.54e-06
polygon 78          5 4.41923e+03      2.64e-07
polygon 79          4 2.43914e+03      1.46e-07
polygon 80          5 4.71226e+03      2.81e-07
polygon 81        217 2.22687e+06      1.33e-04
polygon 82         63 5.45427e+04      3.25e-06
polygon 83          6 4.61991e+03      2.76e-07
polygon 84          6 1.47370e+04      8.79e-07
polygon 85          6 1.35588e+04      8.09e-07
polygon 86         51 9.00805e+04      5.37e-06
polygon 87          4 1.55335e+03      9.27e-08
polygon 88         32 4.34625e+04      2.59e-06
polygon 89        146 5.46576e+05      3.26e-05
polygon 90         36 7.39133e+04      4.41e-06
polygon 91         42 9.17378e+04      5.47e-06
polygon 92        141 1.10143e+06      6.57e-05
polygon 93         96 2.55421e+05      1.52e-05
polygon 94         75 3.74798e+04      2.24e-06
polygon 95         71 9.11194e+05      5.44e-05
polygon 96          5 4.25220e+03      2.54e-07
polygon 97         48 1.10263e+05      6.58e-06
polygon 98          6 1.00670e+04      6.01e-07
polygon 99         33 2.35513e+04      1.41e-06
polygon 100         4 1.39953e+02      8.35e-09
polygon 101       120 3.80319e+05      2.27e-05
polygon 102        19 3.13896e+04      1.87e-06
polygon 103        42 1.21247e+05      7.23e-06
polygon 104        24 3.83865e+04      2.29e-06
polygon 105        88 4.57022e+05      2.73e-05
polygon 106        20 1.78068e+04      1.06e-06
polygon 107        20 2.39368e+04      1.43e-06
polygon 108         5 6.64860e+03      3.97e-07
polygon 109         5 5.41661e+03      3.23e-07
polygon 110        53 4.54957e+05      2.71e-05
polygon 111       263 1.76196e+07      1.05e-03
polygon 112         4 6.76374e+03      4.04e-07
polygon 113        17 5.83732e+03      3.48e-07
polygon 114        25 2.16843e+05      1.29e-05
polygon 115         9 3.13706e+03      1.87e-07
polygon 116        10 1.13374e+04      6.76e-07
polygon 117        45 1.05289e+05      6.28e-06
polygon 118         7 4.71437e+03      2.81e-07
polygon 119       527 4.88599e+07      2.91e-03
polygon 120       632 1.19875e+08      7.15e-03
polygon 121        68 3.72752e+06      2.22e-04
polygon 122        10 1.01946e+05      6.08e-06
polygon 123        19 8.27040e+04      4.93e-06
polygon 124        17 4.01684e+04      2.40e-06
polygon 125        11 4.06518e+04      2.43e-06
polygon 126       111 1.46837e+06      8.76e-05
polygon 127       110 3.73961e+06      2.23e-04
polygon 128        19 1.91715e+04      1.14e-06
polygon 129        73 3.61882e+06      2.16e-04
polygon 130        10 3.05396e+04      1.82e-06
polygon 131         6 1.63086e+04      9.73e-07
polygon 132        81 2.65410e+05      1.58e-05
polygon 133         8 2.10497e+04      1.26e-06
polygon 134         9 2.23051e+04      1.33e-06
polygon 135        11 1.96429e+04      1.17e-06
polygon 136       145 7.13724e+06      4.26e-04
polygon 137        60 1.45303e+05      8.67e-06
polygon 138        74 2.06450e+06      1.23e-04
polygon 139        36 2.64395e+04      1.58e-06
polygon 140       926 2.12401e+08      1.27e-02
polygon 141        25 2.21142e+05      1.32e-05
polygon 142         6 6.85335e+03      4.09e-07
polygon 143        31 1.67739e+06      1.00e-04
polygon 144         7 8.96845e+03      5.35e-07
polygon 145        12 6.31109e+04      3.77e-06
polygon 146       202 2.25183e+07      1.34e-03
polygon 147        46 2.39836e+06      1.43e-04
polygon 148        34 1.06861e+04      6.38e-07
polygon 149         8 4.62274e+04      2.76e-06
polygon 150         7 3.16257e+04      1.89e-06
polygon 151         5 6.47214e+03      3.86e-07
polygon 152        12 2.17322e+04      1.30e-06
polygon 153         5 7.20136e+03      4.30e-07
polygon 154       160 1.11856e+06      6.67e-05
polygon 155       105 3.97161e+05      2.37e-05
polygon 156        14 3.77546e+05      2.25e-05
polygon 157        27 1.21328e+06      7.24e-05
polygon 158       132 7.32320e+05      4.37e-05
polygon 159        52 6.46488e+04      3.86e-06
polygon 160        59 5.31644e+06      3.17e-04
polygon 161        48 1.76605e+06      1.05e-04
polygon 162        34 5.03181e+04      3.00e-06
polygon 163        49 1.83632e+04      1.10e-06
polygon 164        19 5.31559e+03      3.17e-07
polygon 165       246 3.09440e+06      1.85e-04
polygon 166        28 1.99191e+05      1.19e-05
polygon 167        19 4.51980e+05      2.70e-05
polygon 168        14 5.66638e+04      3.38e-06
polygon 169        12 1.09882e+05      6.56e-06
polygon 170        41 4.25466e+04      2.54e-06
polygon 171       189 1.69035e+06      1.01e-04
polygon 172       118 2.32814e+05      1.39e-05
polygon 173         7 2.79374e+04      1.67e-06
polygon 174        53 1.72586e+06      1.03e-04
polygon 175        13 6.36463e+04      3.80e-06
polygon 176       156 1.14531e+06      6.83e-05
polygon 177        47 9.13932e+05      5.45e-05
polygon 178        62 3.95152e+06      2.36e-04
polygon 179       155 7.75116e+05      4.62e-05
polygon 180        14 4.20349e+04      2.51e-06
polygon 181        18 5.14007e+03      3.07e-07
polygon 182        31 7.44696e+05      4.44e-05
polygon 183        18 4.11037e+05      2.45e-05
polygon 184        23 7.72702e+03      4.61e-07
polygon 185         8 3.85828e+04      2.30e-06
polygon 186       180 7.46362e+06      4.45e-04
polygon 187        14 2.75557e+05      1.64e-05
polygon 188         4 9.17061e+03      5.47e-07
polygon 189         9 9.64342e+03      5.75e-07
polygon 190         9 6.16694e+04      3.68e-06
polygon 191        10 1.05264e+05      6.28e-06
polygon 192         8 8.74118e+04      5.22e-06
polygon 193         5 1.83999e+04      1.10e-06
polygon 194         5 3.32417e+03      1.98e-07
polygon 195        13 3.15953e+04      1.88e-06
polygon 196        67 3.93589e+05      2.35e-05
polygon 197         4 2.84280e+03      1.70e-07
polygon 198        16 4.94144e+03      2.95e-07
polygon 199         4 1.27360e+03      7.60e-08
polygon 200         8 1.67265e+04      9.98e-07
polygon 201        12 2.45940e+04      1.47e-06
polygon 202        12 5.95411e+04      3.55e-06
polygon 203        14 2.19831e+03      1.31e-07
polygon 204        14 4.32480e+03      2.58e-07
polygon 205        17 7.75234e+03      4.63e-07
polygon 206        13 1.86854e+03      1.11e-07
polygon 207        34 3.85424e+06      2.30e-04
polygon 208         9 3.58530e+03      2.14e-07
polygon 209        15 1.41276e+04      8.43e-07
polygon 210        27 1.42520e+04      8.50e-07
polygon 211        38 2.66059e+04      1.59e-06
polygon 212        22 4.51365e+03      2.69e-07
polygon 213        96 5.26123e+05      3.14e-05
polygon 214        60 1.00574e+05      6.00e-06
polygon 215        31 7.13409e+04      4.26e-06
polygon 216        37 1.08935e+06      6.50e-05
polygon 217       179 8.26972e+05      4.93e-05
polygon 218        59 1.99001e+05      1.19e-05
polygon 219        47 2.81875e+05      1.68e-05
polygon 220       115 3.13327e+05      1.87e-05
polygon 221       133 4.76117e+05      2.84e-05
polygon 222        97 1.63408e+07      9.75e-04
polygon 223        19 6.38976e+03      3.81e-07
polygon 224        10 7.75421e+03      4.63e-07
polygon 225       204 1.42141e+06      8.48e-05
polygon 226       125 2.33616e+06      1.39e-04
polygon 227        31 2.58857e+04      1.54e-06
polygon 228        25 2.06725e+04      1.23e-06
polygon 229        87 1.25180e+06      7.47e-05
polygon 230        38 4.03858e+04      2.41e-06
polygon 231        10 5.04629e+04      3.01e-06
polygon 232         6 1.12888e+04      6.73e-07
polygon 233        40 1.56849e+05      9.36e-06
polygon 234        66 5.25038e+04      3.13e-06
polygon 235         8 1.10747e+04      6.61e-07
polygon 236        10 1.50784e+03      9.00e-08
polygon 237        14 4.55332e+03      2.72e-07
polygon 238        41 4.12940e+04      2.46e-06
polygon 239         7 3.04017e+03      1.81e-07
polygon 240        19 7.53923e+03      4.50e-07
polygon 241        18 8.35187e+03      4.98e-07
polygon 242        26 5.16261e+05      3.08e-05
polygon 243        13 9.24908e+04      5.52e-06
polygon 244        25 4.18653e+04      2.50e-06
polygon 245         7 3.83476e+03      2.29e-07
polygon 246        82 4.38420e+05      2.62e-05
polygon 247       164 3.46334e+06      2.07e-04
polygon 248        11 5.20050e+03      3.10e-07
polygon 249        13 3.27494e+04      1.95e-06
polygon 250         6 3.01213e+04      1.80e-06
polygon 251        13 2.03114e+05      1.21e-05
polygon 252        38 2.87869e+04      1.72e-06
polygon 253        14 4.11781e+03      2.46e-07
polygon 254        44 1.67050e+05      9.97e-06
polygon 255        11 6.66399e+04      3.98e-06
polygon 256       129 2.29310e+06      1.37e-04
polygon 257        22 6.48307e+03      3.87e-07
polygon 258       107 1.06884e+06      6.38e-05
polygon 259         9 2.30080e+04      1.37e-06
polygon 260        34 9.10976e+03      5.43e-07
polygon 261        72 1.08609e+05      6.48e-06
polygon 262        64 2.19815e+05      1.31e-05
polygon 263        25 2.57976e+05      1.54e-05
polygon 264        26 4.60002e+04      2.74e-06
polygon 265        57 8.30086e+04      4.95e-06
polygon 266        83 1.14012e+06      6.80e-05
polygon 267        11 3.01000e+04      1.80e-06
polygon 268        14 1.30459e+05      7.78e-06
polygon 269        22 2.37055e+05      1.41e-05
polygon 270        22 1.84821e+05      1.10e-05
enclosing rectangle: [512010.4, 928107.4] x [9621858, 9833989] units
                     (416100 x 212100 units)
Window area = 16761600000 square units
Fraction of frame area: 0.19</code></pre>
</div>
</div>
<p>Plotting the result to confirm it is correct:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(fire_month_owin)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="hand-on-ex3_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="computing-spatio-temporal-kde" class="level3">
<h3 class="anchored" data-anchor-id="computing-spatio-temporal-kde">Computing spatio-temporal KDE</h3>
<p><code>spattemp.density()</code> estimates the density over space and time jointly. With no bandwidths supplied it selects both automatically, an isotropic spatial bandwidth <code>h</code> and a temporal bandwidth <code>lambda</code>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>st_kde <span class="ot">&lt;-</span> <span class="fu">spattemp.density</span>(fire_month_owin)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(st_kde)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Spatiotemporal Kernel Density Estimate

Bandwidths
  h = 19142.08 (spatial)
  lambda = 0.0265 (temporal)

No. of observations
  898 

Spatial bound
  Type: polygonal
  2D enclosure: [512010.4, 928107.4] x [9621858, 9833989]

Temporal bound
  [1, 12]

Evaluation
  128 x 128 x 12 trivariate lattice
  Density range: [1.087787e-39, 6.380959e-10]</code></pre>
</div>
</div>
</section>
<section id="plotting-the-spatio-temporal-kde-object" class="level3">
<h3 class="anchored" data-anchor-id="plotting-the-spatio-temporal-kde-object">Plotting the spatio-temporal KDE object</h3>
<p>The estimate is a stack of surfaces, one per time slice. Plotting July to December shows the second half of the year, when the fires concentrate:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>tims <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">7</span>, <span class="dv">8</span>, <span class="dv">9</span>, <span class="dv">10</span>, <span class="dv">11</span>, <span class="dv">12</span>)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfcol =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">3</span>))</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> tims) {</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>(st_kde, i,</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">override.par =</span> <span class="cn">FALSE</span>,</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">fix.range =</span> <span class="cn">TRUE</span>,</span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">main =</span> <span class="fu">paste</span>(<span class="st">"KDE at month"</span>, i))</span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="hand-on-ex3_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="1152"></p>
</figure>
</div>
</div>
</div>
<p><code>fix.range = TRUE</code> holds the colour scale constant across the six panels, so a given colour means the same density in every month. Without it each panel is scaled to its own range and the months cannot be compared.</p>
</section>
</section>
<section id="computing-stkde-by-day-of-year" class="level2">
<h2 class="anchored" data-anchor-id="computing-stkde-by-day-of-year">Computing STKDE by Day of Year</h2>
<p>The same estimation is repeated at daily resolution.</p>
<section id="creating-ppp-object" class="level3">
<h3 class="anchored" data-anchor-id="creating-ppp-object">Creating ppp object</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>fire_yday_ppp <span class="ot">&lt;-</span> fire_sf <span class="sc">%&gt;%</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(DayofYear) <span class="sc">%&gt;%</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.ppp</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="including-owin-object-1" class="level3">
<h3 class="anchored" data-anchor-id="including-owin-object-1">Including owin object</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>fire_yday_owin <span class="ot">&lt;-</span> fire_yday_ppp[kbb_owin]</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fire_yday_owin)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Marked planar point pattern:  898 points
Average intensity 5.357491e-08 points per square unit

Coordinates are given to 10 decimal places

marks are numeric, of type 'double'
Summary:
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
   10.0   218.5   259.5   247.7   288.0   360.0 

Window: polygonal boundary
270 separate polygons (no holes)
             vertices        area relative.area
polygon 1        8736 1.15970e+10      6.92e-01
polygon 2           6 5.15790e+04      3.08e-06
polygon 3           7 9.35325e+04      5.58e-06
polygon 4          20 1.26679e+04      7.56e-07
polygon 5          23 9.26107e+04      5.53e-06
polygon 6          18 4.98850e+05      2.98e-05
polygon 7          30 3.37290e+04      2.01e-06
polygon 8          54 3.25363e+05      1.94e-05
polygon 9          33 1.30250e+06      7.77e-05
polygon 10        132 1.16490e+06      6.95e-05
polygon 11         69 1.91355e+05      1.14e-05
polygon 12        117 1.51905e+05      9.06e-06
polygon 13         95 1.14409e+05      6.83e-06
polygon 14         22 4.54503e+03      2.71e-07
polygon 15         25 1.18153e+04      7.05e-07
polygon 16        131 1.52345e+05      9.09e-06
polygon 17         39 1.07779e+04      6.43e-07
polygon 18         54 3.46837e+05      2.07e-05
polygon 19         72 2.15853e+05      1.29e-05
polygon 20         16 1.85061e+03      1.10e-07
polygon 21         79 1.05702e+05      6.31e-06
polygon 22         20 4.26450e+03      2.54e-07
polygon 23        119 1.64729e+05      9.83e-06
polygon 24         40 1.16146e+04      6.93e-07
polygon 25         16 3.52284e+03      2.10e-07
polygon 26        328 3.08592e+06      1.84e-04
polygon 27        191 2.36937e+06      1.41e-04
polygon 28         77 8.82506e+04      5.27e-06
polygon 29         49 6.13179e+04      3.66e-06
polygon 30        121 7.64910e+04      4.56e-06
polygon 31          5 1.73815e+04      1.04e-06
polygon 32       5944 4.61753e+09      2.75e-01
polygon 33          4 6.39020e+03      3.81e-07
polygon 34         16 1.18396e+05      7.06e-06
polygon 35          5 2.11407e+04      1.26e-06
polygon 36         11 3.52360e+04      2.10e-06
polygon 37         13 6.20570e+04      3.70e-06
polygon 38          8 1.23128e+04      7.35e-07
polygon 39          5 9.16907e+03      5.47e-07
polygon 40         31 1.54528e+06      9.22e-05
polygon 41         13 6.02786e+04      3.60e-06
polygon 42         19 8.71573e+04      5.20e-06
polygon 43         15 6.16242e+04      3.68e-06
polygon 44          8 1.56726e+04      9.35e-07
polygon 45          6 1.35363e+04      8.08e-07
polygon 46          4 4.29360e+03      2.56e-07
polygon 47         23 1.77052e+05      1.06e-05
polygon 48         45 4.35839e+04      2.60e-06
polygon 49          5 6.83224e+03      4.08e-07
polygon 50          5 6.68328e+03      3.99e-07
polygon 51          5 2.25570e+03      1.35e-07
polygon 52          7 2.61716e+04      1.56e-06
polygon 53          9 1.20125e+04      7.17e-07
polygon 54          8 2.24884e+04      1.34e-06
polygon 55          6 1.21058e+04      7.22e-07
polygon 56          5 8.79539e+03      5.25e-07
polygon 57          9 2.28045e+04      1.36e-06
polygon 58          6 9.20554e+03      5.49e-07
polygon 59         49 1.00131e+05      5.97e-06
polygon 60          5 4.47493e+03      2.67e-07
polygon 61          4 2.88084e+03      1.72e-07
polygon 62          4 3.66452e+03      2.19e-07
polygon 63         69 9.92186e+04      5.92e-06
polygon 64          5 3.03623e+03      1.81e-07
polygon 65          6 1.05413e+04      6.29e-07
polygon 66          8 9.42911e+03      5.63e-07
polygon 67         13 6.94883e+04      4.15e-06
polygon 68         34 2.01331e+05      1.20e-05
polygon 69        227 1.23408e+06      7.36e-05
polygon 70          4 2.59824e+03      1.55e-07
polygon 71          7 8.47540e+03      5.06e-07
polygon 72          5 8.12486e+03      4.85e-07
polygon 73         95 2.08341e+05      1.24e-05
polygon 74         18 7.79145e+04      4.65e-06
polygon 75         24 1.59007e+04      9.49e-07
polygon 76          4 8.81028e+02      5.26e-08
polygon 77         43 4.25653e+04      2.54e-06
polygon 78          5 4.41923e+03      2.64e-07
polygon 79          4 2.43914e+03      1.46e-07
polygon 80          5 4.71226e+03      2.81e-07
polygon 81        217 2.22687e+06      1.33e-04
polygon 82         63 5.45427e+04      3.25e-06
polygon 83          6 4.61991e+03      2.76e-07
polygon 84          6 1.47370e+04      8.79e-07
polygon 85          6 1.35588e+04      8.09e-07
polygon 86         51 9.00805e+04      5.37e-06
polygon 87          4 1.55335e+03      9.27e-08
polygon 88         32 4.34625e+04      2.59e-06
polygon 89        146 5.46576e+05      3.26e-05
polygon 90         36 7.39133e+04      4.41e-06
polygon 91         42 9.17378e+04      5.47e-06
polygon 92        141 1.10143e+06      6.57e-05
polygon 93         96 2.55421e+05      1.52e-05
polygon 94         75 3.74798e+04      2.24e-06
polygon 95         71 9.11194e+05      5.44e-05
polygon 96          5 4.25220e+03      2.54e-07
polygon 97         48 1.10263e+05      6.58e-06
polygon 98          6 1.00670e+04      6.01e-07
polygon 99         33 2.35513e+04      1.41e-06
polygon 100         4 1.39953e+02      8.35e-09
polygon 101       120 3.80319e+05      2.27e-05
polygon 102        19 3.13896e+04      1.87e-06
polygon 103        42 1.21247e+05      7.23e-06
polygon 104        24 3.83865e+04      2.29e-06
polygon 105        88 4.57022e+05      2.73e-05
polygon 106        20 1.78068e+04      1.06e-06
polygon 107        20 2.39368e+04      1.43e-06
polygon 108         5 6.64860e+03      3.97e-07
polygon 109         5 5.41661e+03      3.23e-07
polygon 110        53 4.54957e+05      2.71e-05
polygon 111       263 1.76196e+07      1.05e-03
polygon 112         4 6.76374e+03      4.04e-07
polygon 113        17 5.83732e+03      3.48e-07
polygon 114        25 2.16843e+05      1.29e-05
polygon 115         9 3.13706e+03      1.87e-07
polygon 116        10 1.13374e+04      6.76e-07
polygon 117        45 1.05289e+05      6.28e-06
polygon 118         7 4.71437e+03      2.81e-07
polygon 119       527 4.88599e+07      2.91e-03
polygon 120       632 1.19875e+08      7.15e-03
polygon 121        68 3.72752e+06      2.22e-04
polygon 122        10 1.01946e+05      6.08e-06
polygon 123        19 8.27040e+04      4.93e-06
polygon 124        17 4.01684e+04      2.40e-06
polygon 125        11 4.06518e+04      2.43e-06
polygon 126       111 1.46837e+06      8.76e-05
polygon 127       110 3.73961e+06      2.23e-04
polygon 128        19 1.91715e+04      1.14e-06
polygon 129        73 3.61882e+06      2.16e-04
polygon 130        10 3.05396e+04      1.82e-06
polygon 131         6 1.63086e+04      9.73e-07
polygon 132        81 2.65410e+05      1.58e-05
polygon 133         8 2.10497e+04      1.26e-06
polygon 134         9 2.23051e+04      1.33e-06
polygon 135        11 1.96429e+04      1.17e-06
polygon 136       145 7.13724e+06      4.26e-04
polygon 137        60 1.45303e+05      8.67e-06
polygon 138        74 2.06450e+06      1.23e-04
polygon 139        36 2.64395e+04      1.58e-06
polygon 140       926 2.12401e+08      1.27e-02
polygon 141        25 2.21142e+05      1.32e-05
polygon 142         6 6.85335e+03      4.09e-07
polygon 143        31 1.67739e+06      1.00e-04
polygon 144         7 8.96845e+03      5.35e-07
polygon 145        12 6.31109e+04      3.77e-06
polygon 146       202 2.25183e+07      1.34e-03
polygon 147        46 2.39836e+06      1.43e-04
polygon 148        34 1.06861e+04      6.38e-07
polygon 149         8 4.62274e+04      2.76e-06
polygon 150         7 3.16257e+04      1.89e-06
polygon 151         5 6.47214e+03      3.86e-07
polygon 152        12 2.17322e+04      1.30e-06
polygon 153         5 7.20136e+03      4.30e-07
polygon 154       160 1.11856e+06      6.67e-05
polygon 155       105 3.97161e+05      2.37e-05
polygon 156        14 3.77546e+05      2.25e-05
polygon 157        27 1.21328e+06      7.24e-05
polygon 158       132 7.32320e+05      4.37e-05
polygon 159        52 6.46488e+04      3.86e-06
polygon 160        59 5.31644e+06      3.17e-04
polygon 161        48 1.76605e+06      1.05e-04
polygon 162        34 5.03181e+04      3.00e-06
polygon 163        49 1.83632e+04      1.10e-06
polygon 164        19 5.31559e+03      3.17e-07
polygon 165       246 3.09440e+06      1.85e-04
polygon 166        28 1.99191e+05      1.19e-05
polygon 167        19 4.51980e+05      2.70e-05
polygon 168        14 5.66638e+04      3.38e-06
polygon 169        12 1.09882e+05      6.56e-06
polygon 170        41 4.25466e+04      2.54e-06
polygon 171       189 1.69035e+06      1.01e-04
polygon 172       118 2.32814e+05      1.39e-05
polygon 173         7 2.79374e+04      1.67e-06
polygon 174        53 1.72586e+06      1.03e-04
polygon 175        13 6.36463e+04      3.80e-06
polygon 176       156 1.14531e+06      6.83e-05
polygon 177        47 9.13932e+05      5.45e-05
polygon 178        62 3.95152e+06      2.36e-04
polygon 179       155 7.75116e+05      4.62e-05
polygon 180        14 4.20349e+04      2.51e-06
polygon 181        18 5.14007e+03      3.07e-07
polygon 182        31 7.44696e+05      4.44e-05
polygon 183        18 4.11037e+05      2.45e-05
polygon 184        23 7.72702e+03      4.61e-07
polygon 185         8 3.85828e+04      2.30e-06
polygon 186       180 7.46362e+06      4.45e-04
polygon 187        14 2.75557e+05      1.64e-05
polygon 188         4 9.17061e+03      5.47e-07
polygon 189         9 9.64342e+03      5.75e-07
polygon 190         9 6.16694e+04      3.68e-06
polygon 191        10 1.05264e+05      6.28e-06
polygon 192         8 8.74118e+04      5.22e-06
polygon 193         5 1.83999e+04      1.10e-06
polygon 194         5 3.32417e+03      1.98e-07
polygon 195        13 3.15953e+04      1.88e-06
polygon 196        67 3.93589e+05      2.35e-05
polygon 197         4 2.84280e+03      1.70e-07
polygon 198        16 4.94144e+03      2.95e-07
polygon 199         4 1.27360e+03      7.60e-08
polygon 200         8 1.67265e+04      9.98e-07
polygon 201        12 2.45940e+04      1.47e-06
polygon 202        12 5.95411e+04      3.55e-06
polygon 203        14 2.19831e+03      1.31e-07
polygon 204        14 4.32480e+03      2.58e-07
polygon 205        17 7.75234e+03      4.63e-07
polygon 206        13 1.86854e+03      1.11e-07
polygon 207        34 3.85424e+06      2.30e-04
polygon 208         9 3.58530e+03      2.14e-07
polygon 209        15 1.41276e+04      8.43e-07
polygon 210        27 1.42520e+04      8.50e-07
polygon 211        38 2.66059e+04      1.59e-06
polygon 212        22 4.51365e+03      2.69e-07
polygon 213        96 5.26123e+05      3.14e-05
polygon 214        60 1.00574e+05      6.00e-06
polygon 215        31 7.13409e+04      4.26e-06
polygon 216        37 1.08935e+06      6.50e-05
polygon 217       179 8.26972e+05      4.93e-05
polygon 218        59 1.99001e+05      1.19e-05
polygon 219        47 2.81875e+05      1.68e-05
polygon 220       115 3.13327e+05      1.87e-05
polygon 221       133 4.76117e+05      2.84e-05
polygon 222        97 1.63408e+07      9.75e-04
polygon 223        19 6.38976e+03      3.81e-07
polygon 224        10 7.75421e+03      4.63e-07
polygon 225       204 1.42141e+06      8.48e-05
polygon 226       125 2.33616e+06      1.39e-04
polygon 227        31 2.58857e+04      1.54e-06
polygon 228        25 2.06725e+04      1.23e-06
polygon 229        87 1.25180e+06      7.47e-05
polygon 230        38 4.03858e+04      2.41e-06
polygon 231        10 5.04629e+04      3.01e-06
polygon 232         6 1.12888e+04      6.73e-07
polygon 233        40 1.56849e+05      9.36e-06
polygon 234        66 5.25038e+04      3.13e-06
polygon 235         8 1.10747e+04      6.61e-07
polygon 236        10 1.50784e+03      9.00e-08
polygon 237        14 4.55332e+03      2.72e-07
polygon 238        41 4.12940e+04      2.46e-06
polygon 239         7 3.04017e+03      1.81e-07
polygon 240        19 7.53923e+03      4.50e-07
polygon 241        18 8.35187e+03      4.98e-07
polygon 242        26 5.16261e+05      3.08e-05
polygon 243        13 9.24908e+04      5.52e-06
polygon 244        25 4.18653e+04      2.50e-06
polygon 245         7 3.83476e+03      2.29e-07
polygon 246        82 4.38420e+05      2.62e-05
polygon 247       164 3.46334e+06      2.07e-04
polygon 248        11 5.20050e+03      3.10e-07
polygon 249        13 3.27494e+04      1.95e-06
polygon 250         6 3.01213e+04      1.80e-06
polygon 251        13 2.03114e+05      1.21e-05
polygon 252        38 2.87869e+04      1.72e-06
polygon 253        14 4.11781e+03      2.46e-07
polygon 254        44 1.67050e+05      9.97e-06
polygon 255        11 6.66399e+04      3.98e-06
polygon 256       129 2.29310e+06      1.37e-04
polygon 257        22 6.48307e+03      3.87e-07
polygon 258       107 1.06884e+06      6.38e-05
polygon 259         9 2.30080e+04      1.37e-06
polygon 260        34 9.10976e+03      5.43e-07
polygon 261        72 1.08609e+05      6.48e-06
polygon 262        64 2.19815e+05      1.31e-05
polygon 263        25 2.57976e+05      1.54e-05
polygon 264        26 4.60002e+04      2.74e-06
polygon 265        57 8.30086e+04      4.95e-06
polygon 266        83 1.14012e+06      6.80e-05
polygon 267        11 3.01000e+04      1.80e-06
polygon 268        14 1.30459e+05      7.78e-06
polygon 269        22 2.37055e+05      1.41e-05
polygon 270        22 1.84821e+05      1.10e-05
enclosing rectangle: [512010.4, 928107.4] x [9621858, 9833989] units
                     (416100 x 212100 units)
Window area = 16761600000 square units
Fraction of frame area: 0.19</code></pre>
</div>
</div>
</section>
<section id="computing-the-stkde" class="level3">
<h3 class="anchored" data-anchor-id="computing-the-stkde">Computing the STKDE</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>kde_yday <span class="ot">&lt;-</span> <span class="fu">spattemp.density</span>(fire_yday_owin)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(kde_yday)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Spatiotemporal Kernel Density Estimate

Bandwidths
  h = 19142.08 (spatial)
  lambda = 6.4675 (temporal)

No. of observations
  898 

Spatial bound
  Type: polygonal
  2D enclosure: [512010.4, 928107.4] x [9621858, 9833989]

Temporal bound
  [10, 360]

Evaluation
  128 x 128 x 351 trivariate lattice
  Density range: [1.833835e-28, 1.863931e-12]</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Plotting every day is not useful
</div>
</div>
<div class="callout-body-container callout-body">
<p><code>plot(kde_yday)</code> draws <strong>one panel per time slice</strong>, and the daily lattice has over three hundred of them. The result is an unreadable wall of tiny plots that takes a long time to render.</p>
<p>A selection of days is plotted instead, chosen to span the fire season identified in the monthly analysis:</p>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>days <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">200</span>, <span class="dv">230</span>, <span class="dv">260</span>, <span class="dv">280</span>, <span class="dv">300</span>, <span class="dv">330</span>)</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfcol =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">3</span>))</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> days) {</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>(kde_yday, i,</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">override.par =</span> <span class="cn">FALSE</span>,</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">fix.range =</span> <span class="cn">TRUE</span>,</span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">main =</span> <span class="fu">paste</span>(<span class="st">"KDE at day"</span>, i))</span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="hand-on-ex3_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" width="1152"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="computing-stkde-by-day-of-year-improved-method" class="level2">
<h2 class="anchored" data-anchor-id="computing-stkde-by-day-of-year-improved-method">Computing STKDE by Day of Year: Improved Method</h2>
<p><code>BOOT.spattemp()</code> of <strong>sparr</strong> selects the bandwidths by bootstrap estimation of the mean integrated squared error, returning an isotropic scalar spatial bandwidth and a scalar temporal bandwidth. This is a better-founded choice than the defaults used above:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="fu">BOOT.spattemp</span>(fire_yday_owin)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Initialising...Done.
Optimising...
h = 19142.08 ; lambda = 15.2269 
h = 21056.29 ; lambda = 15.2269 
h = 19142.08 ; lambda = 1929.435 
h = 19620.63 ; lambda = 972.3308 
h = 19859.91 ; lambda = 493.7788 
h = 19979.54 ; lambda = 254.5029 
h = 20039.36 ; lambda = 134.8649 
h = 20069.27 ; lambda = 75.04589 
h = 20084.23 ; lambda = 45.13639 
h = 20091.7 ; lambda = 30.18165 
h = 22005.91 ; lambda = 30.18165 
h = 21289.95 ; lambda = 26.44296 
h = 22254.54 ; lambda = 11.48821 
h = 21713.83 ; lambda = 16.16157 
h = 21947.5 ; lambda = 27.37763 
h = 21724.69 ; lambda = 24.33995 
h = 22148.57 ; lambda = 14.05856 
h = 21933.91 ; lambda = 17.15466 
h = 21944.78 ; lambda = 25.33304 
h = 21887.04 ; lambda = 23.04017 
h = 22096.26 ; lambda = 15.85488 
h = 21817.59 ; lambda = 22.21868 
h = 21770.71 ; lambda = 28.10419 
h = 21893.11 ; lambda = 19.89204 
h = 21823.66 ; lambda = 19.07055 
h = 21839.5 ; lambda = 20.06296 
h = 21915.03 ; lambda = 17.73632 
h = 21841.95 ; lambda = 21.09809 
Done.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>          h      lambda 
21893.11332    19.89204 </code></pre>
</div>
</div>
<section id="computing-spatio-temporal-kde-1" class="level3">
<h3 class="anchored" data-anchor-id="computing-spatio-temporal-kde-1">Computing spatio-temporal KDE</h3>
<p>The STKDE is now derived using the <code>h</code> and <code>lambda</code> values the bootstrap returned, rounded:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>kde_yday <span class="ot">&lt;-</span> <span class="fu">spattemp.density</span>(fire_yday_owin,</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>                             <span class="at">h =</span> <span class="dv">21900</span>,</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>                             <span class="at">lambda =</span> <span class="fl">19.9</span>)</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(kde_yday)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Spatiotemporal Kernel Density Estimate

Bandwidths
  h = 21900 (spatial)
  lambda = 19.9 (temporal)

No. of observations
  898 

Spatial bound
  Type: polygonal
  2D enclosure: [512010.4, 928107.4] x [9621858, 9833989]

Temporal bound
  [10, 360]

Evaluation
  128 x 128 x 351 trivariate lattice
  Density range: [5.667365e-19, 1.142683e-12]</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Do not carry the textbook’s numbers across
</div>
</div>
<div class="callout-body-container callout-body">
<p>The textbook reaches <code>h = 9105</code> and hardcodes <code>h = 9000</code>. The bootstrap run above returns h = 21893 on this data, roughly 2.4 times larger, because the study area here includes Belitung and holds more events, and the optimal spatial bandwidth scales with both.</p>
<p>The temporal bandwidth is the opposite case: lambda = 19.89 against the textbook’s 18.85, almost the same, because the fire season has the same length either way. Copying <code>h = 9000</code> across would have imposed a kernel far too narrow for this window and produced a spuriously spiky surface.</p>
</div>
</div>
</section>
<section id="plotting-the-output-spatio-temporal-kde" class="level3">
<h3 class="anchored" data-anchor-id="plotting-the-output-spatio-temporal-kde">Plotting the output spatio-temporal KDE</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfcol =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">3</span>))</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> days) {</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot</span>(kde_yday, i,</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">override.par =</span> <span class="cn">FALSE</span>,</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">fix.range =</span> <span class="cn">TRUE</span>,</span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">main =</span> <span class="fu">paste</span>(<span class="st">"KDE at day"</span>, i))</span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="hand-on-ex3_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid figure-img" width="1152"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="spatio-temporal-point-patterns-analysis-stpp-methods" class="level2">
<h2 class="anchored" data-anchor-id="spatio-temporal-point-patterns-analysis-stpp-methods">Spatio-temporal Point Patterns Analysis: stpp Methods</h2>
<p>This section uses functions of the <strong>stpp</strong> package to perform spatio-temporal point patterns analysis.</p>
<section id="preparing-spatio-temporal-point-process-object-of-stpp" class="level3">
<h3 class="anchored" data-anchor-id="preparing-spatio-temporal-point-process-object-of-stpp">Preparing spatio-temporal point process object of stpp</h3>
<p><strong>Step 1</strong>: Extracting the forest fire coordinates from the fire point events.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>coords <span class="ot">&lt;-</span> <span class="fu">st_coordinates</span>(fire_sf)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>Step 2</strong>: Creating a data frame by combining the x- and y-coordinates with the temporal event. The temporal event must be an integer.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>fire_df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span> coords[, <span class="dv">1</span>],</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">y =</span> coords[, <span class="dv">2</span>],</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">t =</span> fire_sf<span class="sc">$</span><span class="st">`</span><span class="at">DayofYear</span><span class="st">`</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>Step 3</strong>: Creating the <code>stpp</code> spatio-temporal object with <code>as.3dpoints()</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>fire_stpp <span class="ot">&lt;-</span> <span class="fu">as.3dpoints</span>(fire_df)</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(fire_stpp)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "stpp"</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(fire_stpp)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="hand-on-ex3_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="computing-spatio-temporal-k-function" class="level3">
<h3 class="anchored" data-anchor-id="computing-spatio-temporal-k-function">Computing spatio-temporal K-function</h3>
<p><code>STIKhat()</code> computes the space-time inhomogeneous K-function:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>kbb_stik <span class="ot">&lt;-</span> <span class="fu">STIKhat</span>(fire_stpp)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><code>plotK()</code> visualises the output:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plotK</span>(kbb_stik)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="guide-to-interpret-the-plot" class="level3">
<h3 class="anchored" data-anchor-id="guide-to-interpret-the-plot">Guide to interpret the plot</h3>
<ul>
<li>If the contours show high values for small values of <em>u</em> and <em>v</em>, it suggests clustering at short spatial and temporal distances, meaning events occur close to each other in both space and time.</li>
<li>If the contours are flat or show low values, it indicates a more random distribution or a lack of significant clustering at those distances.</li>
</ul>
<p>The spatial and temporal extent of clustering can be understood by observing how rapidly the contours increase or decrease along the axes: the spacing and values of the contour lines show at which distances clustering occurs.</p>
</section>
</section>
<section id="reference" class="level2">
<h2 class="anchored" data-anchor-id="reference">Reference</h2>
<ul>
<li>Kam, T. S. <em>R for Geospatial Data Science and Analytics</em>, <a href="https://r4gdsa.netlify.app/chap06">Chapter 6: Spatio-Temporal Point Patterns Analysis</a>.</li>
<li>Peter Hall (1990) “Using the Bootstrap to Estimate Mean Squared Error and Select Smoothing Parameter in Nonparametric Problems”, <em>Journal of Multivariate Analysis</em>, Vol. 32, pp.&nbsp;177-203.</li>
<li>González, J. A. et al.&nbsp;(2016) <a href="https://www.sciencedirect.com/science/article/abs/pii/S2211675316301130">“Spatio-temporal point process statistics: A review”</a>, <em>Spatial Statistics</em>, Vol. 18, Part B, pp.&nbsp;505-544.</li>
<li><a href="https://tilmandavies.github.io/sparr/index.html">sparr: Spatial and Spatiotemporal Relative Risk</a></li>
<li><a href="https://www.jstatsoft.org/article/view/v053i02">stpp: An R Package for Plotting, Simulating and Analyzing Spatio-Temporal Point Patterns</a>, <em>Journal of Statistical Software</em>, Vol. 53, Issue 2.</li>
</ul>


</section>

</main> <!-- /main -->
<!-- =====================================================================
     Language toggle (EN / 中文)
     Take-home Exercise 1 | ISSS626

     Both language versions of every prose block are present in the HTML;
     this switch only changes which one is displayed, so switching is
     instant and needs no server and no second render.

     The choice is stored in localStorage under one key shared by the
     technical report and the executive summary, so moving between the two
     documents keeps the selected language.

     Three things are NOT handled by the .en / .zh markup and are handled
     here instead:

       1. Placement. On the technical report the site navbar is fixed to the
          top of the viewport, so a `position: fixed` switch would sit on top
          of it. The switch is therefore moved into the navbar's own tool
          slot (`.quarto-navbar-tools`), which is a sibling of the collapsing
          menu and so stays visible at every width. On the slides there is no
          navbar and the switch stays fixed in the corner.

       2. Template chrome. Strings such as the table-of-contents heading and
          the "Author" / "Published" labels are emitted by Quarto's template,
          not by the document body, so no .en / .zh span can reach them. They
          are swapped from the DICT table below.

       3. Figures keep their English titles and axis labels: that text is
          drawn into the PNG by R at render time.
     ===================================================================== -->

<div class="lang-switch" role="group" aria-label="Language / 语言">
  <button type="button" data-lang="en" aria-pressed="true">EN</button>
  <button type="button" data-lang="zh" aria-pressed="false">中文</button>
</div>

<script>
(function () {
  var KEY = "isss626-th1-lang";
  var VALID = { en: 1, zh: 1 };

  // ---- 1. Move the switch into the navbar, where one exists ---------------
  // Done before the first apply() so the switch never paints in the wrong
  // place. `.quarto-navbar-tools` is a sibling of `#navbarCollapse`, not a
  // child, so the switch is not swallowed by the mobile hamburger.
  var sw = document.querySelector(".lang-switch");
  var tools = document.querySelector("#quarto-header .quarto-navbar-tools");
  if (sw && tools) {
    tools.appendChild(sw);
    sw.classList.add("in-navbar");
  }

  // ---- 2. Template chrome -------------------------------------------------
  // Quarto writes these strings itself. Each entry is keyed by the English
  // the template produces; the original is cached on first pass so that
  // switching back to English restores it exactly.
  var DICT = {
    "Contents": "目录",
    "Table of contents": "目录",
    "Author": "作者",
    "Authors": "作者",
    "Published": "发布日期",
    "Modified": "最后修改",
    "Code": "代码",
    "Show All Code": "展开全部代码",
    "Hide All Code": "折叠全部代码",
    "View Source": "查看源文件",
    "Full Screen": "全屏",
    "Close": "关闭",
    "Note": "注",
    "Tip": "提示",
    "Warning": "注意",
    "Important": "要点",
    "Caution": "当心",
    // Navbar. Most pages on this site are English-only in the body, so without
    // these the switch would be present everywhere and do nothing on nine of
    // the eleven pages. Translating the site chrome makes it meaningful on all
    // of them, and keeps the chosen language visible while browsing.
    "Home": "首页",
    "About": "关于",
    "Hands-on Exercise": "课堂练习",
    "In-class Exercise": "堂上练习",
    "Take-home Exercise": "课后作业",
    "Search": "搜索",
    "ISSS626-GAA": "ISSS626-GAA"
  };

  var CHROME_SEL = [
    "#toc-title",
    "nav[role=doc-toc] > h2",
    ".quarto-title-meta-heading",
    ".code-tools-button",
    "#quarto-code-tools-menu",
    ".dropdown-menu .dropdown-item",
    ".callout-title-container",
    ".callout-caption",
    "#quarto-header .navbar .menu-text",
    "#quarto-header .navbar .dropdown-item",
    "#quarto-search .aa-DetachedSearchButtonPlaceholder",
    "#quarto-search [title]"
  ].join(",");

  // Text nodes are collected once. Holding the nodes themselves (rather than
  // re-querying) keeps the swap independent of how Quarto nests the labels,
  // and avoids touching any markup inside them, such as the Bootstrap icon
  // in the code-tools button.
  var chrome = null;
  function collectChrome() {
    var out = [];
    var hosts = document.querySelectorAll(CHROME_SEL);
    for (var i = 0; i < hosts.length; i++) {
      var walker = document.createTreeWalker(hosts[i], NodeFilter.SHOW_TEXT, null);
      var n;
      while ((n = walker.nextNode())) {
        var t = n.nodeValue.trim();
        if (DICT[t]) out.push({ node: n, en: n.nodeValue, zh: n.nodeValue.replace(t, DICT[t]) });
      }
    }
    return out;
  }

  function applyChrome(lang) {
    if (chrome === null) chrome = collectChrome();
    for (var i = 0; i < chrome.length; i++) {
      chrome[i].node.nodeValue = lang === "zh" ? chrome[i].zh : chrome[i].en;
    }
  }

  // ---- 3. The switch itself ----------------------------------------------
  function apply(lang, persist) {
    if (!VALID[lang]) lang = "en";
    document.documentElement.setAttribute("data-lang", lang);
    document.documentElement.setAttribute("lang", lang === "zh" ? "zh-Hans" : "en");
    if (persist) {
      try { localStorage.setItem(KEY, lang); } catch (e) { /* private mode */ }
    }
    applyChrome(lang);
    var btns = document.querySelectorAll(".lang-switch button");
    for (var i = 0; i < btns.length; i++) {
      var on = btns[i].getAttribute("data-lang") === lang;
      btns[i].classList.toggle("active", on);
      btns[i].setAttribute("aria-pressed", on ? "true" : "false");
    }
    // Reveal.js lays slides out once on load; a language change alters
    // block heights, so ask it to re-measure if it is present.
    if (window.Reveal && typeof window.Reveal.layout === "function") {
      window.Reveal.layout();
    }
  }

  var saved = "en";
  try { saved = localStorage.getItem(KEY) || "en"; } catch (e) { /* ignore */ }

  document.addEventListener("click", function (ev) {
    var b = ev.target && ev.target.closest ? ev.target.closest(".lang-switch button") : null;
    if (b) { ev.preventDefault(); apply(b.getAttribute("data-lang"), true); }
  });

  // Keyboard shortcut: Alt+L cycles the language.
  document.addEventListener("keydown", function (ev) {
    if (ev.altKey && (ev.key === "l" || ev.key === "L")) {
      apply(document.documentElement.getAttribute("data-lang") === "zh" ? "en" : "zh", true);
    }
  });

  apply(saved, false);

  // The code-tools dropdown items exist from the start, but the callout
  // labels of any lazily-rendered block may not. One re-collect after load
  // is cheap insurance and keeps the swap correct.
  window.addEventListener("load", function () {
    chrome = null;
    applyChrome(document.documentElement.getAttribute("data-lang"));
  });
})();
</script>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>