{
  "hash": "0f947d8d6e390fa36c6b3195953a4a0f",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"In-class Exercise 4: Geographically Weighted Summary Statistics\"\nauthor: \"Ji Guofang\"\ndate: \"September 18, 2026\"\ndate-modified: \"last-modified\"\nformat:\n  html:\n    toc: true\n    toc-depth: 4\n    toc-expand: true\nexecute:\n  echo: true\n  eval: true\n  warning: false\n  freeze: auto\neditor: visual\n---\n\n## Overview\n\nLesson 4 defines a neighbourhood twice over. The first definition is combinatorial: two counties are neighbours or they are not, by shared boundary or by a distance threshold. That definition produces the neighbour lists and row-standardised weights built throughout [Hands-on Exercise 4](../../hand-on-ex/hand-on-ex4/hand-on-ex4.qmd), together with the spatially lagged variables that follow from them, and none of it is taught again here.\n\nThe second definition is continuous. A kernel replaces the in-or-out decision with a weight that decays with distance, and a bandwidth sets how quickly it decays. Every observation then contributes to every location, just by progressively less. This in-class exercise works entirely in that second branch:\n\n- selecting a bandwidth by cross-validation and by AIC, adaptive and fixed,\n- computing geographically weighted summary statistics, meaning the local mean, the local median and the rest of the robust family, with `gwss()` of **GWmodel**,\n- computing geographically weighted correlation, and reading it against the single global correlation that conventional analysis would report.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(sf, ggstatsplot, tmap, tidyverse, knitr, GWmodel)\n```\n:::\n\n\n**spdep** is absent from that list, and its absence is the point: no neighbour list is constructed anywhere in this document. The kernel *is* the weighting scheme, so the object that **spdep** exists to build is never needed. **GWmodel** supplies the geographically weighted methods, and **ggstatsplot** supplies the global correlation test that they are compared against.\n\n## The Data\n\nThe same two files as the hands-on exercise, but more of the attribute table is retained:\n\n| Dataset | Description |\n|----|----|\n| `Hunan` | County boundary layer of Hunan province, China, in ESRI shapefile format |\n| `Hunan_2012.csv` | Selected local development indicators for Hunan in 2012 |\n\n## Inputs Carried Over from Hands-on Exercise 4\n\nImporting the shapefile with `st_read()`, importing the csv with `read_csv()`, and attaching one to the other with `left_join()` were all covered in [Hands-on Exercise 4](../../hand-on-ex/hand-on-ex4/hand-on-ex4.qmd). The code is repeated here only so that this document runs on its own:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhunan_sf <- st_read(dsn = \"data/geospatial\",\n                    layer = \"Hunan\") %>%\n  left_join(read_csv(\"data/aspatial/Hunan_2012.csv\",\n                     show_col_types = FALSE),\n            by = \"County\") %>%\n  select(1:3, 7, 15, 16, 31, 32)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `Hunan' from data source \n  `C:\\Users\\Imgigi\\Desktop\\629\\in-class-ex\\in-class-ex4\\data\\geospatial' \n  using driver `ESRI Shapefile'\nSimple feature collection with 88 features and 7 fields\nGeometry type: POLYGON\nDimension:     XY\nBounding box:  xmin: 108.7831 ymin: 24.6342 xmax: 114.2544 ymax: 30.12812\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n:::\n\n\nThe import header is left visible: 88 polygon features with seven attribute fields, bounded by 108.7831–114.2544 E and 24.6342–30.1281 N, on geodetic CRS WGS 84. The layer is left unprojected throughout, since `longlat = TRUE` in the **GWmodel** calls below makes them compute great circle distances in kilometres from those coordinates.\n\nOne thing does differ from the hands-on version, and it is not cosmetic. There the join kept `select(1:4, 7, 15)`, the identifiers and GDPPC alone, because a spatial lag needs exactly one variable. Here the selection is widened to eight columns, adding `GIO` (gross industrial output), `Agri` and `Service`, because the correlation section needs a second variable to correlate GDPPC *against*:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(hunan_sf)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 88\nColumns: 9\n$ NAME_2   <chr> \"Changde\", \"Changde\", \"Changde\", \"Changde\", \"Changde\", \"Chang…\n$ ID_3     <int> 21098, 21100, 21101, 21102, 21103, 21104, 21109, 21110, 21111…\n$ NAME_3   <chr> \"Anxiang\", \"Hanshou\", \"Jinshi\", \"Li\", \"Linli\", \"Shimen\", \"Liu…\n$ County   <chr> \"Anxiang\", \"Hanshou\", \"Jinshi\", \"Li\", \"Linli\", \"Shimen\", \"Liu…\n$ GDPPC    <dbl> 23667, 20981, 34592, 24473, 25554, 27137, 63118, 62202, 70666…\n$ GIO      <dbl> 5108.9, 13491.0, 10935.0, 18402.0, 8214.0, 17795.0, 99254.0, …\n$ Agri     <dbl> 4524.410, 6545.350, 2562.460, 7562.340, 3583.910, 5266.510, 1…\n$ Service  <dbl> 14100.0, 17727.0, 7525.0, 53160.0, 7031.0, 6981.0, 26617.8, 1…\n$ geometry <POLYGON [°]> POLYGON ((112.0625 29.75523..., POLYGON ((112.2288 29…\n```\n\n\n:::\n:::\n\n\n## From **sf** to **sp**\n\n**GWmodel** predates the simple features standard and its functions expect a `Spatial*DataFrame` from the older **sp** class system. `as_Spatial()` performs the conversion:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhunan_sp <- hunan_sf %>%\n  as_Spatial()\n```\n:::\n\n\nTwo objects now describe the same 88 counties. `hunan_sp` is the input for **GWmodel**, and `hunan_sf` remains the object **tmap** is given at the end. Results come back from `gwss()` in the order of the rows that went in, which is what makes the `cbind()` in the mapping sections legitimate. That join is positional rather than by key, so nothing between here and there may reorder or filter either object.\n\n## Determining the Bandwidth\n\nThe bandwidth is the one parameter that decides how local \"local\" is, and it is chosen by optimisation rather than by hand. `bw.gwr()` searches for the value that minimises a chosen criterion. CV is leave-one-out cross-validation, scoring how well each location is predicted from its neighbours; AIC penalises model complexity instead.\n\nThe search is run against the intercept-only model `GDPPC ~ 1`, since what is wanted is a bandwidth for describing GDPPC locally, not for regressing it on anything.\n\n### Adaptive bandwidth\n\nAn adaptive bandwidth holds the *number* of neighbours constant and lets the radius stretch or contract, so the kernel covers as many counties in the sparse west as in the dense north-east:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbw_CV_adaptive <- bw.gwr(GDPPC ~ 1,\n                         data = hunan_sp,\n                         approach = \"CV\",\n                         adaptive = TRUE,\n                         kernel = \"bisquare\",\n                         longlat = TRUE)\n\nbw_AIC_adaptive <- bw.gwr(GDPPC ~ 1,\n                          data = hunan_sp,\n                          approach = \"AIC\",\n                          adaptive = TRUE,\n                          kernel = \"bisquare\",\n                          longlat = TRUE)\n```\n:::\n\n\n### Fixed bandwidth\n\nA fixed bandwidth holds the *radius* constant instead, and the neighbour count varies with local density:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbw_CV_fixed <- bw.gwr(GDPPC ~ 1,\n                      data = hunan_sp,\n                      approach = \"CV\",\n                      adaptive = FALSE,\n                      kernel = \"bisquare\",\n                      longlat = TRUE)\n\nbw_AIC_fixed <- bw.gwr(GDPPC ~ 1,\n                       data = hunan_sp,\n                       approach = \"AIC\",\n                       adaptive = FALSE,\n                       kernel = \"bisquare\",\n                       longlat = TRUE)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntibble(Bandwidth = c(\"Adaptive\", \"Adaptive\", \"Fixed\", \"Fixed\"),\n       Criterion = c(\"CV\", \"AIC\", \"CV\", \"AIC\"),\n       Value = c(bw_CV_adaptive, bw_AIC_adaptive,\n                 bw_CV_fixed, bw_AIC_fixed),\n       Unit = c(\"nearest neighbours\", \"nearest neighbours\", \"km\", \"km\")) %>%\n  kable(digits = 2)\n```\n\n::: {.cell-output-display}\n\n\n|Bandwidth |Criterion |  Value|Unit               |\n|:---------|:---------|------:|:------------------|\n|Adaptive  |CV        |  22.00|nearest neighbours |\n|Adaptive  |AIC       |  22.00|nearest neighbours |\n|Fixed     |CV        |  76.29|km                 |\n|Fixed     |AIC       | 160.55|km                 |\n\n\n:::\n:::\n\n\nThe two criteria behave differently depending on which kind of bandwidth they are searching over.\n\nOn the adaptive side, CV and AIC both settle on 22 nearest neighbours. Agreement between two criteria that optimise different things is the strongest evidence available here that 22 is a feature of the data rather than an artefact of the search. It amounts to a quarter of the province, which is a defensible reading of \"local\".\n\nOn the fixed side, CV returns 76.3 km and AIC returns 160.6 km, more than double. That disagreement is diagnostic rather than a failure of either method. Hunan's counties vary greatly in area, so a single radius means a different sample size everywhere it is placed. CV, scored point by point, chases the radius that fits the densest parts, while AIC tolerates a much broader kernel for the province as a whole. When a fixed bandwidth makes the two criteria disagree this sharply and an adaptive one makes them agree exactly, the adaptive specification is the one the data supports.\n\n## Geographically Weighted Summary Statistics\n\n`gwss()` computes the summary statistics at every location, each one weighted by the kernel. Setting `quantile = TRUE` adds the robust family, meaning the local median, interquartile range and quantile imbalance, alongside the moment-based statistics:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngwstat <- gwss(data = hunan_sp,\n               vars = \"GDPPC\",\n               bw = bw_AIC_adaptive,\n               kernel = \"bisquare\",\n               quantile = TRUE,\n               adaptive = TRUE,\n               longlat = TRUE)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnames(as.data.frame(gwstat$SDF))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"GDPPC_LM\"     \"GDPPC_LSD\"    \"GDPPC_LVar\"   \"GDPPC_LSKe\"   \"GDPPC_LCV\"   \n[6] \"GDPPC_Median\" \"GDPPC_IQR\"    \"GDPPC_QI\"    \n```\n\n\n:::\n:::\n\n\nEight surfaces for a single variable: local mean, standard deviation, variance, skewness and coefficient of variation from the moment-based side, then median, IQR and quantile imbalance from the robust side. Each is a vector of 88 values, one per county, rather than a single number.\n\n### Preparing the output\n\n`gwss()` returns its results in the `SDF` slot as a `Spatial*DataFrame`. Extracting the data table and binding it column-wise to `hunan_sf` restores a mappable `sf` object:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngwstat_df <- as.data.frame(gwstat$SDF)\n\nhunan_gstat <- cbind(hunan_sf, gwstat_df)\n```\n:::\n\n\n### Visualising the geographically weighted mean\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntm_shape(hunan_gstat) +\n  tm_polygons(fill = \"GDPPC_LM\",\n              fill.scale = tm_scale_intervals(\n                style = \"quantile\",\n                n = 5,\n                values = \"brewer.blues\"),\n              fill.legend = tm_legend(\n                title = \"Local mean\")) +\n  tm_borders(col = \"grey70\", lwd = 0.4) +\n  tm_title(\"Geographically weighted mean of GDPPC, 22 nearest neighbours\",\n           size = 1.1)\n```\n\n::: {.cell-output-display}\n![](in-class-ex4_files/figure-html/unnamed-chunk-11-1.png){width=864}\n:::\n:::\n\n\n### The local mean against the global one\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntibble(Statistic = c(\"Global mean\", \"Local mean, minimum\", \"Local mean, maximum\",\n                     \"Global median\", \"Local median, minimum\", \"Local median, maximum\"),\n       GDPPC = c(mean(hunan_sf$GDPPC),\n                 min(hunan_gstat$GDPPC_LM), max(hunan_gstat$GDPPC_LM),\n                 median(hunan_sf$GDPPC),\n                 min(hunan_gstat$GDPPC_Median), max(hunan_gstat$GDPPC_Median))) %>%\n  kable(digits = 0, format.args = list(big.mark = \",\"))\n```\n\n::: {.cell-output-display}\n\n\n|Statistic             |  GDPPC|\n|:---------------------|------:|\n|Global mean           | 24,405|\n|Local mean, minimum   | 13,689|\n|Local mean, maximum   | 49,006|\n|Global median         | 20,433|\n|Local median, minimum | 11,580|\n|Local median, maximum | 41,491|\n\n\n:::\n:::\n\n\nConventional analysis would report one number for Hunan, a mean GDPPC of 24,405 yuan. The geographically weighted mean replaces it with 88, running from 13,689 around Wugang in Shaoyang to 49,006 at Changsha, a 3.6-fold spread the single figure conceals entirely. This is spatial non-stationarity made measurable: the provincial average describes nowhere in particular, because the north-east corridor and the south-western uplands are not samples from the same population.\n\nThe smoothing is substantial and deliberate. Raw GDPPC ranges from 8,497 to 88,656, so the local mean surface compresses a 10-fold spread into a 3.6-fold one. What survives that compression is the regional signal, and what is removed is the county-level idiosyncrasy a spatial lag would have retained.\n\n### Robust statistics: local mean against local median\n\nThe moment-based and robust families are computed from the same kernel, so comparing them isolates the effect of the outliers rather than the effect of location:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm_map <- tm_shape(hunan_gstat) +\n  tm_polygons(fill = \"GDPPC_LM\",\n              fill.scale = tm_scale_intervals(\n                style = \"quantile\", n = 5, values = \"brewer.blues\"),\n              fill.legend = tm_legend(title = \"Local mean\")) +\n  tm_borders(col = \"grey70\", lwd = 0.4) +\n  tm_title(\"Local mean\", size = 1.0)\n\nmed_map <- tm_shape(hunan_gstat) +\n  tm_polygons(fill = \"GDPPC_Median\",\n              fill.scale = tm_scale_intervals(\n                style = \"quantile\", n = 5, values = \"brewer.blues\"),\n              fill.legend = tm_legend(title = \"Local median\")) +\n  tm_borders(col = \"grey70\", lwd = 0.4) +\n  tm_title(\"Local median\", size = 1.0)\n\ntmap_arrange(lm_map, med_map, asp = 1, ncol = 2)\n```\n\n::: {.cell-output-display}\n![](in-class-ex4_files/figure-html/unnamed-chunk-13-1.png){width=1152}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(hunan_gstat$GDPPC_LM / hunan_gstat$GDPPC_Median)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n 0.9186  1.0918  1.1473  1.1737  1.2298  1.6355 \n```\n\n\n:::\n:::\n\n\nThe two maps share a pattern but not a level. The ratio of local mean to local median exceeds 1 almost everywhere, reaching 1.64. In the neighbourhoods around Changsha the weighted mean sits 64% above the weighted median, because a handful of very rich counties pull it upward while the median ignores them by construction.\n\nThat gap is itself the finding. Where mean and median agree, the local distribution is symmetric and either statistic describes the neighbourhood honestly. Where they diverge this far, the neighbourhood contains counties unlike their surroundings, and the mean surface is reporting their influence rather than the typical county. The robust surface is the more defensible description of the north-east, and the divergence between the two is more informative than either alone.\n\n## The Effect of the Bandwidth\n\nRepeating the computation under the fixed bandwidth shows what the choice made in the previous section actually bought:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngwstat_fixed <- gwss(data = hunan_sp,\n                     vars = \"GDPPC\",\n                     bw = bw_AIC_fixed,\n                     kernel = \"bisquare\",\n                     adaptive = FALSE,\n                     quantile = FALSE,\n                     longlat = TRUE)\n\nhunan_gstat_fixed <- cbind(hunan_sf, as.data.frame(gwstat_fixed$SDF))\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nadaptive_map <- tm_shape(hunan_gstat) +\n  tm_polygons(fill = \"GDPPC_LM\",\n              fill.scale = tm_scale_intervals(\n                style = \"quantile\", n = 5, values = \"brewer.blues\"),\n              fill.legend = tm_legend(title = \"Local mean\")) +\n  tm_borders(col = \"grey70\", lwd = 0.4) +\n  tm_title(\"Adaptive, 22 neighbours\", size = 1.0)\n\nfixed_map <- tm_shape(hunan_gstat_fixed) +\n  tm_polygons(fill = \"GDPPC_LM\",\n              fill.scale = tm_scale_intervals(\n                style = \"quantile\", n = 5, values = \"brewer.blues\"),\n              fill.legend = tm_legend(title = \"Local mean\")) +\n  tm_borders(col = \"grey70\", lwd = 0.4) +\n  tm_title(\"Fixed, 160.6 km\", size = 1.0)\n\ntmap_arrange(adaptive_map, fixed_map, asp = 1, ncol = 2)\n```\n\n::: {.cell-output-display}\n![](in-class-ex4_files/figure-html/unnamed-chunk-16-1.png){width=1152}\n:::\n:::\n\n\nThe 160.6 km fixed kernel produces a local mean surface spanning 14,259 to 47,833, close to the adaptive result but reached for a different reason. A fixed radius over Hunan's uneven county sizes draws on roughly thirty counties in the compact north-east and barely a dozen in the large western ones, so the western estimates rest on fewest observations exactly where the counties are largest. The CV bandwidth of 76.3 km makes this visible: at that radius the local mean runs from 10,135 to 72,045, a surface so close to the raw data that it has stopped summarising anything.\n\nThe adaptive kernel removes that dependence by construction, which is why it is the appropriate specification for administrative areas of unequal size, the usual case.\n\n## Geographically Weighted Correlation\n\nThe same kernel machinery applies to a statistic computed from two variables. The question is whether the relationship between GDP per capita and gross industrial output holds with equal strength across the province.\n\n### The conventional analysis first\n\n`ggscatterstats()` gives the global answer, one coefficient for all 88 counties, with its test:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggscatterstats(data = hunan_sf %>% st_drop_geometry(),\n               x = GIO,\n               y = GDPPC,\n               xlab = \"Gross Industrial Output\",\n               ylab = \"GDP per capita\",\n               label.var = County,\n               label.expression = GIO > 20000 & GDPPC > 50000,\n               point.label.args = list(alpha = 0.7, size = 4, color = \"grey50\"),\n               xfill = \"#CC79A7\",\n               yfill = \"#009E73\",\n               title = \"Relationship between GDP per capita and Gross Industrial Output\")\n```\n\n::: {.cell-output-display}\n![](in-class-ex4_files/figure-html/unnamed-chunk-17-1.png){width=864}\n:::\n:::\n\n\nPearson's *r* = 0.77 and clearly significant, a strong positive relationship, and the analysis would conventionally stop there.\n\n### Determining the bandwidth\n\nThe bandwidth for a two-variable statistic is selected from the corresponding regression, so the formula now carries `GIO` on the right-hand side:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbw_corr <- bw.gwr(GDPPC ~ GIO,\n                  data = hunan_sp,\n                  approach = \"AICc\",\n                  adaptive = TRUE)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbw_corr\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 84\n```\n\n\n:::\n:::\n\n\n### Computing the correlation surface\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngwstats_corr <- gwss(hunan_sp,\n                     vars = c(\"GDPPC\", \"GIO\"),\n                     bw = bw_corr,\n                     kernel = \"bisquare\",\n                     adaptive = TRUE,\n                     longlat = TRUE)\n```\n:::\n\n\nTwo variables produce the five univariate surfaces twice over, followed by three bivariate ones. They are selected by name rather than by column position, so that a change of `quantile` or of `vars` cannot silently shift the wrong columns into the map:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngwcorr_df <- as.data.frame(gwstats_corr$SDF) %>%\n  select(gwCorr = Corr_GDPPC.GIO,\n         gwSpearman = Spearman_rho_GDPPC.GIO)\n\nhunan_corr <- cbind(hunan_sf, gwcorr_df)\n```\n:::\n\n\n### Visualising the local Spearman coefficient\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntm_shape(hunan_corr) +\n  tm_polygons(fill = \"gwSpearman\",\n              fill.scale = tm_scale_intervals(\n                style = \"quantile\",\n                n = 5,\n                values = \"brewer.blues\"),\n              fill.legend = tm_legend(\n                title = \"Local Spearman's rho\")) +\n  tm_borders(col = \"grey70\", lwd = 0.4) +\n  tm_title(\"Geographically weighted correlation, GDPPC and GIO\", size = 1.1)\n```\n\n::: {.cell-output-display}\n![](in-class-ex4_files/figure-html/unnamed-chunk-22-1.png){width=864}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntibble(Coefficient = c(\"Pearson\", \"Spearman\"),\n       Global = c(cor(hunan_sf$GDPPC, hunan_sf$GIO),\n                  cor(hunan_sf$GDPPC, hunan_sf$GIO, method = \"spearman\")),\n       `Local minimum` = c(min(hunan_corr$gwCorr), min(hunan_corr$gwSpearman)),\n       `Local maximum` = c(max(hunan_corr$gwCorr), max(hunan_corr$gwSpearman))) %>%\n  kable(digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|Coefficient | Global| Local minimum| Local maximum|\n|:-----------|------:|-------------:|-------------:|\n|Pearson     |  0.765|         0.682|         0.761|\n|Spearman    |  0.732|         0.579|         0.733|\n\n\n:::\n:::\n\n\n::: callout-warning\n## The bandwidth has flattened the surface\n\nThe selected bandwidth is 84 of 88 counties. Every local correlation is therefore computed from almost the entire province, and the result is what that implies: local Pearson spans 0.682 to 0.761 around a global 0.765, and local Spearman 0.579 to 0.733 around a global 0.732. The map above is close to a constant.\n\nThis is not a null finding about Hunan. It is a consequence of where the bandwidth came from. `bw.gwr()` selected 84 as the bandwidth at which a *regression* of GDPPC on GIO is best supported, and a near-global bandwidth is the correct answer to that question when the relationship is genuinely strong everywhere. But the statistic being mapped is not that regression, and a criterion chosen for one is not automatically valid for the other.\n:::\n\nRecomputing on the bandwidth the data itself supported earlier, the 22 neighbours on which CV and AIC agreed, asks the intended question:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngwstats_local <- gwss(hunan_sp,\n                      vars = c(\"GDPPC\", \"GIO\"),\n                      bw = bw_AIC_adaptive,\n                      kernel = \"bisquare\",\n                      adaptive = TRUE,\n                      longlat = TRUE)\n\nhunan_corr22 <- cbind(hunan_sf,\n                      as.data.frame(gwstats_local$SDF) %>%\n                        select(gwCorr = Corr_GDPPC.GIO,\n                               gwSpearman = Spearman_rho_GDPPC.GIO))\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncorr84 <- tm_shape(hunan_corr) +\n  tm_polygons(fill = \"gwCorr\",\n              fill.scale = tm_scale_intervals(\n                style = \"fixed\",\n                breaks = c(0, 0.2, 0.4, 0.6, 0.8, 1),\n                values = \"brewer.blues\"),\n              fill.legend = tm_legend(title = \"Local r\")) +\n  tm_borders(col = \"grey70\", lwd = 0.4) +\n  tm_title(\"bw = 84 neighbours\", size = 1.0)\n\ncorr22 <- tm_shape(hunan_corr22) +\n  tm_polygons(fill = \"gwCorr\",\n              fill.scale = tm_scale_intervals(\n                style = \"fixed\",\n                breaks = c(0, 0.2, 0.4, 0.6, 0.8, 1),\n                values = \"brewer.blues\"),\n              fill.legend = tm_legend(title = \"Local r\")) +\n  tm_borders(col = \"grey70\", lwd = 0.4) +\n  tm_title(\"bw = 22 neighbours\", size = 1.0)\n\ntmap_arrange(corr84, corr22, asp = 1, ncol = 2)\n```\n\n::: {.cell-output-display}\n![](in-class-ex4_files/figure-html/unnamed-chunk-25-1.png){width=1152}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(hunan_corr22$gwCorr)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n 0.1768  0.5631  0.6583  0.6351  0.7507  0.8744 \n```\n\n\n:::\n:::\n\n\nOn the same colour scale the left map is one shade and the right map is four. At 22 neighbours the local Pearson correlation runs from 0.18 to 0.87, and local Spearman from 0.12 to 0.92. The relationship the global coefficient reports as uniformly strong is strong in some parts of Hunan and close to absent in others.\n\nBoth maps are correct at their own bandwidth, and they answer different questions. The left one asks whether industrial output predicts GDP per capita across Hunan, and the answer is yes, consistently. The right one asks whether a county's prosperity tracks its industry *among its own neighbours*, and the answer is that it depends where the county is. In the industrial north-east the two move together closely, while in the west a county's GDP per capita owes comparatively little to its industrial output.\n\nThe conclusion concerns method rather than Hunan. Bandwidth is not a nuisance parameter to be delegated to a selection routine. It declares the scale at which a question is being asked, and a bandwidth optimised for one statistic can suppress precisely the variation another statistic exists to reveal.\n\n## Reference\n\n- Kam, T. S. *ISSS626 Geospatial Analytics and Applications*, Lesson 4: Spatial Weights and Applications.\n- [GWmodel: Geographically-Weighted Models](https://cran.r-project.org/package=GWmodel)\n- Gollini, I., Lu, B., Charlton, M., Brunsdon, C., Harris, P. (2015) [\"GWmodel: An R Package for Exploring Spatial Heterogeneity Using Geographically Weighted Models\"](https://www.jstatsoft.org/article/view/v063i17), *Journal of Statistical Software*, 63(17).\n- Brunsdon, C., Fotheringham, A. S., Charlton, M. (2002) \"Geographically weighted summary statistics: a framework for localised exploratory data analysis\", *Computers, Environment and Urban Systems*, 26(6), 501–524.\n- [ggstatsplot](https://indrajeetpatil.github.io/ggstatsplot/)\n- [tmap: Thematic Maps in R](https://r-tmap.github.io/tmap/)\n",
    "supporting": [
      "in-class-ex4_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}